/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import ec.edu.ups.sistemabiblioteca.enums.Cargo;
import ec.edu.ups.sistemabiblioteca.enums.Turno;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class ActualizarBibliotecario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarBibliotecario
     */
    public ActualizarBibliotecario() {
        initComponents();
        
        jComboBoxCargoAc.removeAllItems();
        jComboBoxTurnoAc.removeAllItems();

        for (Cargo cargo : Cargo.values()) {
            jComboBoxCargoAc.addItem(cargo.name());
        }

        for (Turno turno : Turno.values()) {
            jComboBoxTurnoAc.addItem(turno.name());
        }
    }

    public JButton getjButtonActBBCedula() {
        return jButtonActBBCedula;
    }

    public void setjButtonActBBCedula(JButton jButtonActBBCedula) {
        this.jButtonActBBCedula = jButtonActBBCedula;
    }

    public JButton getjButtonActBCancelar() {
        return jButtonActBCancelar;
    }

    public void setjButtonActBCancelar(JButton jButtonActBCancelar) {
        this.jButtonActBCancelar = jButtonActBCancelar;
    }

    public JButton getjButtonActualizarB() {
        return jButtonActualizarB;
    }

    public void setjButtonActualizarB(JButton jButtonActualizarB) {
        this.jButtonActualizarB = jButtonActualizarB;
    }

    public JTextField getjTextFieldActBApellido() {
        return jTextFieldActBApellido;
    }

    public void setjTextFieldActBApellido(JTextField jTextFieldActBApellido) {
        this.jTextFieldActBApellido = jTextFieldActBApellido;
    }

    public JTextField getjTextFieldActBCedula() {
        return jTextFieldActBCedula;
    }

    public void setjTextFieldActBCedula(JTextField jTextFieldActBCedula) {
        this.jTextFieldActBCedula = jTextFieldActBCedula;
    }

    public JTextField getjTextFieldActBCodigo() {
        return jTextFieldActBCodigo;
    }

    public void setjTextFieldActBCodigo(JTextField jTextFieldActBCodigo) {
        this.jTextFieldActBCodigo = jTextFieldActBCodigo;
    }

    public JTextField getjTextFieldActBFecha() {
        return jTextFieldActBFecha;
    }

    public void setjTextFieldActBFecha(JTextField jTextFieldActBFecha) {
        this.jTextFieldActBFecha = jTextFieldActBFecha;
    }

    public JTextField getjTextFieldActBNombre() {
        return jTextFieldActBNombre;
    }

    public void setjTextFieldActBNombre(JTextField jTextFieldActBNombre) {
        this.jTextFieldActBNombre = jTextFieldActBNombre;
    }

    public JTextField getjTextFieldActBTelefono() {
        return jTextFieldActBTelefono;
    }

    public void setjTextFieldActBTelefono(JTextField jTextFieldActBTelefono) {
        this.jTextFieldActBTelefono = jTextFieldActBTelefono;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);

    }

    public JComboBox<String> getjComboBoxCargoAc() {
        return jComboBoxCargoAc;
    }

    public void setjComboBoxCargoAc(JComboBox<String> jComboBoxCargoAc) {
        this.jComboBoxCargoAc = jComboBoxCargoAc;
    }

    public JComboBox<String> getjComboBoxTurnoAc() {
        return jComboBoxTurnoAc;
    }

    public void setjComboBoxTurnoAc(JComboBox<String> jComboBoxTurnoAc) {
        this.jComboBoxTurnoAc = jComboBoxTurnoAc;
    }

    public void mostrarInformacion1(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelActualizarBibliotecario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelActBCedula = new javax.swing.JLabel();
        jTextFieldActBCedula = new javax.swing.JTextField();
        jButtonActBBCedula = new javax.swing.JButton();
        jLabelActBNombre = new javax.swing.JLabel();
        jTextFieldActBNombre = new javax.swing.JTextField();
        jLabelActBApellido = new javax.swing.JLabel();
        jTextFieldActBApellido = new javax.swing.JTextField();
        jLabelActBCargo = new javax.swing.JLabel();
        jLabelActBTelefono = new javax.swing.JLabel();
        jTextFieldActBTelefono = new javax.swing.JTextField();
        jLabelActBCodBibliotecario = new javax.swing.JLabel();
        jTextFieldActBCodigo = new javax.swing.JTextField();
        jLabelActBFNacimiento = new javax.swing.JLabel();
        jTextFieldActBFecha = new javax.swing.JTextField();
        jLabelActBTurno = new javax.swing.JLabel();
        jButtonActualizarB = new javax.swing.JButton();
        jButtonActBCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTurnoAc = new javax.swing.JComboBox<>();
        jComboBoxCargoAc = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Bibliotecario");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelActualizarBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelActualizarBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelActualizarBibliotecario.setText("ACTUALIZAR BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualizarBibliotecario, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualizarBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelActBCedula.setText("Cedula:");

        jButtonActBBCedula.setBackground(new java.awt.Color(0, 102, 153));
        jButtonActBBCedula.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActBBCedula.setText("Buscar");
        jButtonActBBCedula.addActionListener(this::jButtonActBBCedulaActionPerformed);

        jLabelActBNombre.setText("Nombre:");

        jLabelActBApellido.setText("Apellido:");

        jLabelActBCargo.setText("Cargo:");

        jLabelActBTelefono.setText("Telefono:");

        jLabelActBCodBibliotecario.setText("Codigo:");

        jLabelActBFNacimiento.setText("Fecha de Nacimiento:");

        jTextFieldActBFecha.addActionListener(this::jTextFieldActBFechaActionPerformed);

        jLabelActBTurno.setText("Turno:");

        jButtonActualizarB.setBackground(new java.awt.Color(0, 102, 153));
        jButtonActualizarB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizarB.setText("ACTUALIZAR");
        jButtonActualizarB.addActionListener(this::jButtonActualizarBActionPerformed);

        jButtonActBCancelar.setText("CANCELAR");
        jButtonActBCancelar.addActionListener(this::jButtonActBCancelarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("AAAA-MM-DD");

        jComboBoxTurnoAc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCargoAc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelActBTelefono)
                            .addContainerGap(263, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelActBCodBibliotecario)
                            .addContainerGap(271, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelActBFNacimiento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxCargoAc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelActBTurno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelActBApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelActBCedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelActBCargo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelActBNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldActBNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldActBApellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldActBTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldActBCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldActBFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldActBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonActBBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButtonActualizarB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonActBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxTurnoAc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActBCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldActBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActBBCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCargoAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBCodBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActBFNacimiento)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTurnoAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizarB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActBFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActBFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActBFechaActionPerformed

    private void jButtonActBBCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActBBCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActBBCedulaActionPerformed

    private void jButtonActBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonActBCancelarActionPerformed

    private void jButtonActualizarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarBActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n", locale);
        jLabelActualizarBibliotecario.setText(bundle.getString("TBliudp"));
        jButtonActualizarB.setText(bundle.getString("bttnUpd"));
        jButtonActBCancelar.setText(bundle.getString("bttnCancelar"));
        jLabelActBCedula.setText(bundle.getString("labelBliCedula"));
        jLabelActBNombre.setText(bundle.getString("labelBliNombre"));
        jLabelActBApellido.setText(bundle.getString("labelBliApellido"));
        jLabelActBCargo.setText(bundle.getString("labelBliCargo"));
        jLabelActBTelefono.setText(bundle.getString("labelBuATelefono"));
        jLabelActBCodBibliotecario.setText(bundle.getString("labelBliCodigo"));
        jLabelActBFNacimiento.setText(bundle.getString("labelBliFN"));
        jLabelActBTurno.setText(bundle.getString("labelBliT"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActBBCedula;
    private javax.swing.JButton jButtonActBCancelar;
    private javax.swing.JButton jButtonActualizarB;
    private javax.swing.JComboBox<String> jComboBoxCargoAc;
    private javax.swing.JComboBox<String> jComboBoxTurnoAc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelActBApellido;
    private javax.swing.JLabel jLabelActBCargo;
    private javax.swing.JLabel jLabelActBCedula;
    private javax.swing.JLabel jLabelActBCodBibliotecario;
    private javax.swing.JLabel jLabelActBFNacimiento;
    private javax.swing.JLabel jLabelActBNombre;
    private javax.swing.JLabel jLabelActBTelefono;
    private javax.swing.JLabel jLabelActBTurno;
    private javax.swing.JLabel jLabelActualizarBibliotecario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldActBApellido;
    private javax.swing.JTextField jTextFieldActBCedula;
    private javax.swing.JTextField jTextFieldActBCodigo;
    private javax.swing.JTextField jTextFieldActBFecha;
    private javax.swing.JTextField jTextFieldActBNombre;
    private javax.swing.JTextField jTextFieldActBTelefono;
    // End of variables declaration//GEN-END:variables
}
