/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class ActualizarBibliotecario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizarBibliotecario
     */
    public ActualizarBibliotecario() {
        initComponents();
    }

    public JButton getjButtonActBBCedula() {
        return jButtonActBBCedula;
    }

    public void setjButtonActBBCedula(JButton jButtonActBBCedula) {
        this.jButtonActBBCedula = jButtonActBBCedula;
    }

    public JButton getjButtonActBCancelar() {
        return jButtonActBCancelar;
    }

    public void setjButtonActBCancelar(JButton jButtonActBCancelar) {
        this.jButtonActBCancelar = jButtonActBCancelar;
    }

    public JButton getjButtonActualizarB() {
        return jButtonActualizarB;
    }

    public void setjButtonActualizarB(JButton jButtonActualizarB) {
        this.jButtonActualizarB = jButtonActualizarB;
    }

    public JTextField getjTextFieldActBApellido() {
        return jTextFieldActBApellido;
    }

    public void setjTextFieldActBApellido(JTextField jTextFieldActBApellido) {
        this.jTextFieldActBApellido = jTextFieldActBApellido;
    }

    public JTextField getjTextFieldActBCargo() {
        return jTextFieldActBCargo;
    }

    public void setjTextFieldActBCargo(JTextField jTextFieldActBCargo) {
        this.jTextFieldActBCargo = jTextFieldActBCargo;
    }

    public JTextField getjTextFieldActBCedula() {
        return jTextFieldActBCedula;
    }

    public void setjTextFieldActBCedula(JTextField jTextFieldActBCedula) {
        this.jTextFieldActBCedula = jTextFieldActBCedula;
    }

    public JTextField getjTextFieldActBCodigo() {
        return jTextFieldActBCodigo;
    }

    public void setjTextFieldActBCodigo(JTextField jTextFieldActBCodigo) {
        this.jTextFieldActBCodigo = jTextFieldActBCodigo;
    }

    public JTextField getjTextFieldActBFecha() {
        return jTextFieldActBFecha;
    }

    public void setjTextFieldActBFecha(JTextField jTextFieldActBFecha) {
        this.jTextFieldActBFecha = jTextFieldActBFecha;
    }

    public JTextField getjTextFieldActBNombre() {
        return jTextFieldActBNombre;
    }

    public void setjTextFieldActBNombre(JTextField jTextFieldActBNombre) {
        this.jTextFieldActBNombre = jTextFieldActBNombre;
    }

    public JTextField getjTextFieldActBTelefono() {
        return jTextFieldActBTelefono;
    }

    public void setjTextFieldActBTelefono(JTextField jTextFieldActBTelefono) {
        this.jTextFieldActBTelefono = jTextFieldActBTelefono;
    }

    public JTextField getjTextFieldActBTurno() {
        return jTextFieldActBTurno;
    }

    public void setjTextFieldActBTurno(JTextField jTextFieldActBTurno) {
        this.jTextFieldActBTurno = jTextFieldActBTurno;
    }
    
        public void mostrarInformacion(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelActualizarBibliotecario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelActBCedula = new javax.swing.JLabel();
        jTextFieldActBCedula = new javax.swing.JTextField();
        jButtonActBBCedula = new javax.swing.JButton();
        jLabelActBNombre = new javax.swing.JLabel();
        jTextFieldActBNombre = new javax.swing.JTextField();
        jLabelActBApellido = new javax.swing.JLabel();
        jTextFieldActBApellido = new javax.swing.JTextField();
        jLabelActBCargo = new javax.swing.JLabel();
        jTextFieldActBCargo = new javax.swing.JTextField();
        jLabelActBTelefono = new javax.swing.JLabel();
        jTextFieldActBTelefono = new javax.swing.JTextField();
        jLabelActBCodBibliotecario = new javax.swing.JLabel();
        jTextFieldActBCodigo = new javax.swing.JTextField();
        jLabelActBFNacimiento = new javax.swing.JLabel();
        jTextFieldActBFecha = new javax.swing.JTextField();
        jLabelActBTurno = new javax.swing.JLabel();
        jTextFieldActBTurno = new javax.swing.JTextField();
        jButtonActualizarB = new javax.swing.JButton();
        jButtonActBCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Bibliotecario");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelActualizarBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelActualizarBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelActualizarBibliotecario.setText("ACTUALIZAR BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualizarBibliotecario, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualizarBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelActBCedula.setText("Cedula:");

        jButtonActBBCedula.setBackground(new java.awt.Color(0, 102, 153));
        jButtonActBBCedula.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActBBCedula.setText("Buscar");
        jButtonActBBCedula.addActionListener(this::jButtonActBBCedulaActionPerformed);

        jLabelActBNombre.setText("Nombre:");

        jLabelActBApellido.setText("Apellido:");

        jLabelActBCargo.setText("Cargo:");

        jLabelActBTelefono.setText("Telefono:");

        jLabelActBCodBibliotecario.setText("Codigo:");

        jLabelActBFNacimiento.setText("Fecha de Nacimiento:");

        jTextFieldActBFecha.addActionListener(this::jTextFieldActBFechaActionPerformed);

        jLabelActBTurno.setText("Turno:");

        jButtonActualizarB.setBackground(new java.awt.Color(0, 102, 153));
        jButtonActualizarB.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizarB.setText("ACTUALIZAR");
        jButtonActualizarB.addActionListener(this::jButtonActualizarBActionPerformed);

        jButtonActBCancelar.setText("CANCELAR");
        jButtonActBCancelar.addActionListener(this::jButtonActBCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelActBTelefono)
                            .addGap(238, 238, 238))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelActBCodBibliotecario)
                            .addGap(246, 246, 246))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelActBFNacimiento)
                            .addGap(173, 173, 173)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelActBTurno)
                        .addComponent(jLabelActBApellido)
                        .addComponent(jLabelActBCedula)
                        .addComponent(jLabelActBCargo)
                        .addComponent(jLabelActBNombre)
                        .addComponent(jTextFieldActBNombre)
                        .addComponent(jTextFieldActBApellido)
                        .addComponent(jTextFieldActBCargo)
                        .addComponent(jTextFieldActBTelefono)
                        .addComponent(jTextFieldActBCodigo)
                        .addComponent(jTextFieldActBFecha)
                        .addComponent(jTextFieldActBTurno)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldActBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonActBBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonActualizarB, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActBCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldActBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActBBCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBCodBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBFNacimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelActBTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldActBTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizarB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActBFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActBFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActBFechaActionPerformed

    private void jButtonActBBCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActBBCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActBBCedulaActionPerformed

    private void jButtonActBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonActBCancelarActionPerformed

    private void jButtonActualizarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActBBCedula;
    private javax.swing.JButton jButtonActBCancelar;
    private javax.swing.JButton jButtonActualizarB;
    private javax.swing.JLabel jLabelActBApellido;
    private javax.swing.JLabel jLabelActBCargo;
    private javax.swing.JLabel jLabelActBCedula;
    private javax.swing.JLabel jLabelActBCodBibliotecario;
    private javax.swing.JLabel jLabelActBFNacimiento;
    private javax.swing.JLabel jLabelActBNombre;
    private javax.swing.JLabel jLabelActBTelefono;
    private javax.swing.JLabel jLabelActBTurno;
    private javax.swing.JLabel jLabelActualizarBibliotecario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldActBApellido;
    private javax.swing.JTextField jTextFieldActBCargo;
    private javax.swing.JTextField jTextFieldActBCedula;
    private javax.swing.JTextField jTextFieldActBCodigo;
    private javax.swing.JTextField jTextFieldActBFecha;
    private javax.swing.JTextField jTextFieldActBNombre;
    private javax.swing.JTextField jTextFieldActBTelefono;
    private javax.swing.JTextField jTextFieldActBTurno;
    // End of variables declaration//GEN-END:variables
}
