/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class BorrarBibliotecario extends javax.swing.JInternalFrame {

    /**
     * Creates new form BorrarBibliotecario
     */
    public BorrarBibliotecario() {
        initComponents();
    }

    public JButton getjButtonEBBCedula() {
        return jButtonEBBCedula;
    }

    public void setjButtonEBBCedula(JButton jButtonEBBCedula) {
        this.jButtonEBBCedula = jButtonEBBCedula;
    }

    public JButton getjButtonEBCancelar() {
        return jButtonEBCancelar;
    }

    public void setjButtonEBCancelar(JButton jButtonEBCancelar) {
        this.jButtonEBCancelar = jButtonEBCancelar;
    }

    public JButton getjButtonEBEliminar() {
        return jButtonEBEliminar;
    }

    public void setjButtonEBEliminar(JButton jButtonEBEliminar) {
        this.jButtonEBEliminar = jButtonEBEliminar;
    }

    public JTextField getjTextFieldEBApellido() {
        return jTextFieldEBApellido;
    }

    public void setjTextFieldEBApellido(JTextField jTextFieldEBApellido) {
        this.jTextFieldEBApellido = jTextFieldEBApellido;
    }

    public JTextField getjTextFieldEBCargo() {
        return jTextFieldEBCargo;
    }

    public void setjTextFieldEBCargo(JTextField jTextFieldEBCargo) {
        this.jTextFieldEBCargo = jTextFieldEBCargo;
    }

    public JTextField getjTextFieldEBCedula() {
        return jTextFieldEBCedula;
    }

    public void setjTextFieldEBCedula(JTextField jTextFieldEBCedula) {
        this.jTextFieldEBCedula = jTextFieldEBCedula;
    }

    public JTextField getjTextFieldEBCodigo() {
        return jTextFieldEBCodigo;
    }

    public void setjTextFieldEBCodigo(JTextField jTextFieldEBCodigo) {
        this.jTextFieldEBCodigo = jTextFieldEBCodigo;
    }

    public JTextField getjTextFieldEBFecha() {
        return jTextFieldEBFecha;
    }

    public void setjTextFieldEBFecha(JTextField jTextFieldEBFecha) {
        this.jTextFieldEBFecha = jTextFieldEBFecha;
    }

    public JTextField getjTextFieldEBNombre() {
        return jTextFieldEBNombre;
    }

    public void setjTextFieldEBNombre(JTextField jTextFieldEBNombre) {
        this.jTextFieldEBNombre = jTextFieldEBNombre;
    }

    public JTextField getjTextFieldEBTelefono() {
        return jTextFieldEBTelefono;
    }

    public void setjTextFieldEBTelefono(JTextField jTextFieldEBTelefono) {
        this.jTextFieldEBTelefono = jTextFieldEBTelefono;
    }

    public JTextField getjTextFieldEBTurno() {
        return jTextFieldEBTurno;
    }

    public void setjTextFieldEBTurno(JTextField jTextFieldEBTurno) {
        this.jTextFieldEBTurno = jTextFieldEBTurno;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);

    }

    public void mostrarInformacion1(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
=======
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabelEBCargo = new javax.swing.JLabel();
        jTextFieldEBCedula = new javax.swing.JTextField();
        jLabelEBFNacimiento = new javax.swing.JLabel();
        jTextFieldEBTurno = new javax.swing.JTextField();
        jLabelEBNombre = new javax.swing.JLabel();
        jTextFieldEBCargo = new javax.swing.JTextField();
        jTextFieldEBFecha = new javax.swing.JTextField();
        jLabelEBTelefono = new javax.swing.JLabel();
        jTextFieldEBNombre = new javax.swing.JTextField();
>>>>>>> main
        jPanel4 = new javax.swing.JPanel();
        jLabelEliminarBibliotecario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelEBCedula = new javax.swing.JLabel();
        jTextFieldEBCedula = new javax.swing.JTextField();
        jButtonEBBCedula = new javax.swing.JButton();
        jLabelEBNombre = new javax.swing.JLabel();
        jTextFieldEBNombre = new javax.swing.JTextField();
        jLabelEBApellido = new javax.swing.JLabel();
        jTextFieldEBApellido = new javax.swing.JTextField();
        jLabelEBCargo = new javax.swing.JLabel();
        jTextFieldEBCargo = new javax.swing.JTextField();
        jLabelEBTelefono = new javax.swing.JLabel();
        jTextFieldEBTelefono = new javax.swing.JTextField();
        jLabelEBCodBibliotecario = new javax.swing.JLabel();
        jTextFieldEBCodigo = new javax.swing.JTextField();
        jLabelEBFNacimiento = new javax.swing.JLabel();
        jTextFieldEBFecha = new javax.swing.JTextField();
        jLabelEBTurno = new javax.swing.JLabel();
        jTextFieldEBTurno = new javax.swing.JTextField();
        jButtonEBEliminar = new javax.swing.JButton();
        jButtonEBCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Bibliotecario");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelEliminarBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelEliminarBibliotecario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminarBibliotecario.setText("ELIMINAR UN BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEliminarBibliotecario, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEliminarBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelEBCedula.setText("Cedula:");

        jButtonEBBCedula.setBackground(new java.awt.Color(0, 102, 153));
        jButtonEBBCedula.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEBBCedula.setText("Buscar");
        jButtonEBBCedula.addActionListener(this::jButtonEBBCedulaActionPerformed);

        jLabelEBNombre.setText("Nombre:");

        jLabelEBApellido.setText("Apellido:");

        jLabelEBCargo.setText("Cargo:");

        jLabelEBTelefono.setText("Telefono:");

        jLabelEBCodBibliotecario.setText("Codigo:");

        jLabelEBFNacimiento.setText("Fecha de Nacimiento:");

        jTextFieldEBFecha.addActionListener(this::jTextFieldEBFechaActionPerformed);

        jLabelEBTurno.setText("Turno:");

        jButtonEBEliminar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonEBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEBEliminar.setText("ELIMINAR");
        jButtonEBEliminar.addActionListener(this::jButtonEBEliminarActionPerformed);

        jButtonEBCancelar.setText("CANCELAR");
        jButtonEBCancelar.addActionListener(this::jButtonEBCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelEBTelefono)
                            .addGap(200, 200, 200))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelEBCodBibliotecario)
                            .addGap(208, 208, 208))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelEBFNacimiento)
                            .addGap(135, 135, 135)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelEBTurno)
                        .addComponent(jLabelEBApellido)
                        .addComponent(jLabelEBCedula)
                        .addComponent(jLabelEBCargo)
                        .addComponent(jLabelEBNombre)
                        .addComponent(jTextFieldEBNombre)
                        .addComponent(jTextFieldEBApellido)
                        .addComponent(jTextFieldEBCargo)
                        .addComponent(jTextFieldEBTelefono)
                        .addComponent(jTextFieldEBCodigo)
                        .addComponent(jTextFieldEBFecha)
                        .addComponent(jTextFieldEBTurno)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextFieldEBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonEBBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonEBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEBCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEBBCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBCodBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBFNacimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEBTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEBTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEBFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEBFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEBFechaActionPerformed

    private void jButtonEBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonEBCancelarActionPerformed

    private void jButtonEBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEBEliminarActionPerformed

    private void jButtonEBBCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEBBCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEBBCedulaActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n", locale);
        jLabelEliminarBibliotecario.setText(bundle.getString("TBlidele"));
        jButtonEBEliminar.setText(bundle.getString("bttnEliminar"));
        jButtonEBCancelar.setText(bundle.getString("bttnCancelar"));
        jButtonEBBCedula.setText(bundle.getString("bttnBuscar"));
        jLabelEBCedula.setText(bundle.getString("labelDBCedula"));
        jLabelEBNombre.setText(bundle.getString("labelDBNombre"));
        jLabelEBApellido.setText(bundle.getString("labelDBApellido"));
        jLabelEBCargo.setText(bundle.getString("labelDBCargo"));
        jLabelEBTelefono.setText(bundle.getString("labelDBTelefono"));
        jLabelEBCodBibliotecario.setText(bundle.getString("labelDBCodigo"));
        jLabelEBFNacimiento.setText(bundle.getString("labelDBFN"));
        jLabelEBTurno.setText(bundle.getString("labelDBT"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEBBCedula;
    private javax.swing.JButton jButtonEBCancelar;
    private javax.swing.JButton jButtonEBEliminar;
    private javax.swing.JLabel jLabelEBApellido;
    private javax.swing.JLabel jLabelEBCargo;
    private javax.swing.JLabel jLabelEBCedula;
    private javax.swing.JLabel jLabelEBCodBibliotecario;
    private javax.swing.JLabel jLabelEBFNacimiento;
    private javax.swing.JLabel jLabelEBNombre;
    private javax.swing.JLabel jLabelEBTelefono;
    private javax.swing.JLabel jLabelEBTurno;
    private javax.swing.JLabel jLabelEliminarBibliotecario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
<<<<<<< HEAD
    private javax.swing.JScrollPane jScrollPane1;
=======
    private javax.swing.JTabbedPane jTabbedPane1;
>>>>>>> main
    private javax.swing.JTextField jTextFieldEBApellido;
    private javax.swing.JTextField jTextFieldEBCargo;
    private javax.swing.JTextField jTextFieldEBCedula;
    private javax.swing.JTextField jTextFieldEBCodigo;
    private javax.swing.JTextField jTextFieldEBFecha;
    private javax.swing.JTextField jTextFieldEBNombre;
    private javax.swing.JTextField jTextFieldEBTelefono;
    private javax.swing.JTextField jTextFieldEBTurno;
    // End of variables declaration//GEN-END:variables
}
