/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class BuscarBibliotecario extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarBibliotecario
     */
    public BuscarBibliotecario() {
        initComponents();
    }

    public JButton getjButtonBBBCedula() {
        return jButtonBBBCedula;
    }

    public void setjButtonBBBCedula(JButton jButtonBBBCedula) {
        this.jButtonBBBCedula = jButtonBBBCedula;
    }
    

    public JTextField getjTextFieldBBApellido() {
        return jTextFieldBBApellido;
    }

    public void setjTextFieldBBApellido(JTextField jTextFieldBBApellido) {
        this.jTextFieldBBApellido = jTextFieldBBApellido;
    }

    public JTextField getjTextFieldBBCargo() {
        return jTextFieldBBCargo;
    }

    public void setjTextFieldBBCargo(JTextField jTextFieldBBCargo) {
        this.jTextFieldBBCargo = jTextFieldBBCargo;
    }

    public JTextField getjTextFieldBBCedula() {
        return jTextFieldBBCedula;
    }

    public void setjTextFieldBBCedula(JTextField jTextFieldBBCedula) {
        this.jTextFieldBBCedula = jTextFieldBBCedula;
    }

    public JTextField getjTextFieldBBCodigo() {
        return jTextFieldBBCodigo;
    }

    public void setjTextFieldBBCodigo(JTextField jTextFieldBBCodigo) {
        this.jTextFieldBBCodigo = jTextFieldBBCodigo;
    }

    public JTextField getjTextFieldBBFecha() {
        return jTextFieldBBFecha;
    }

    public void setjTextFieldBBFecha(JTextField jTextFieldBBFecha) {
        this.jTextFieldBBFecha = jTextFieldBBFecha;
    }

    public JTextField getjTextFieldBBNombre() {
        return jTextFieldBBNombre;
    }

    public void setjTextFieldBBNombre(JTextField jTextFieldBBNombre) {
        this.jTextFieldBBNombre = jTextFieldBBNombre;
    }

    public JTextField getjTextFieldBBTelefono() {
        return jTextFieldBBTelefono;
    }

    public void setjTextFieldBBTelefono(JTextField jTextFieldBBTelefono) {
        this.jTextFieldBBTelefono = jTextFieldBBTelefono;
    }

    public JTextField getjTextFieldBBTurno() {
        return jTextFieldBBTurno;
    }

    public void setjTextFieldBBTurno(JTextField jTextFieldBBTurno) {
        this.jTextFieldBBTurno = jTextFieldBBTurno;
    }
        public void mostrarInformacion(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelBuscarBibliotecario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelBBCedula = new javax.swing.JLabel();
        jTextFieldBBCedula = new javax.swing.JTextField();
        jButtonBBBCedula = new javax.swing.JButton();
        jLabelBBNombre = new javax.swing.JLabel();
        jTextFieldBBNombre = new javax.swing.JTextField();
        jLabelBBApellido = new javax.swing.JLabel();
        jTextFieldBBApellido = new javax.swing.JTextField();
        jLabelBBCargo = new javax.swing.JLabel();
        jTextFieldBBCargo = new javax.swing.JTextField();
        jLabelBBTelefono = new javax.swing.JLabel();
        jTextFieldBBTelefono = new javax.swing.JTextField();
        jLabelBBCodigo = new javax.swing.JLabel();
        jTextFieldBBCodigo = new javax.swing.JTextField();
        jLabelBBFecha = new javax.swing.JLabel();
        jTextFieldBBFecha = new javax.swing.JTextField();
        jLabelBBTurno = new javax.swing.JLabel();
        jTextFieldBBTurno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Biblotecario");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelBuscarBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBuscarBibliotecario.setText("BUSCAR UN BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBuscarBibliotecario)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelBBCedula.setText("Cedula:");

        jButtonBBBCedula.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBBBCedula.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBBBCedula.setText("Guardar");
        jButtonBBBCedula.addActionListener(this::jButtonBBBCedulaActionPerformed);

        jLabelBBNombre.setText("Nombre:");

        jTextFieldBBNombre.setEditable(false);

        jLabelBBApellido.setText("Apellido:");

        jTextFieldBBApellido.setEditable(false);

        jLabelBBCargo.setText("Cargo:");

        jTextFieldBBCargo.setEditable(false);

        jLabelBBTelefono.setText("Telefono:");

        jTextFieldBBTelefono.setEditable(false);

        jLabelBBCodigo.setText("Codigo:");

        jTextFieldBBCodigo.setEditable(false);

        jLabelBBFecha.setText("Fecha de Nacimiento:");

        jTextFieldBBFecha.setEditable(false);

        jLabelBBTurno.setText("Turno:");

        jTextFieldBBTurno.setEditable(false);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelBBTelefono)
                                    .addGap(242, 242, 242))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelBBCodigo)
                                    .addGap(250, 250, 250))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelBBFecha)
                                    .addGap(177, 177, 177)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelBBTurno)
                                .addComponent(jLabelBBApellido)
                                .addComponent(jLabelBBCedula)
                                .addComponent(jLabelBBCargo)
                                .addComponent(jTextFieldBBApellido)
                                .addComponent(jLabelBBNombre)
                                .addComponent(jTextFieldBBNombre)
                                .addComponent(jTextFieldBBCargo)
                                .addComponent(jTextFieldBBTelefono)
                                .addComponent(jTextFieldBBCodigo)
                                .addComponent(jTextFieldBBFecha)
                                .addComponent(jTextFieldBBTurno)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldBBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonBBBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBBCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBBBCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBBTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBBTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBBBCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBBBCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBBBCedulaActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n.mensajes", locale);
        jLabelBuscarBibliotecario.setText(bundle.getString("TBlibus"));
        jButtonBBBCedula.setText(bundle.getString("bttnBuscar"));
        jLabelBBCedula.setText(bundle.getString("labelBusBCedula"));
        jLabelBBNombre.setText(bundle.getString("labelBusBNombre"));
        jLabelBBApellido.setText(bundle.getString("labelBusBApellido"));
        jLabelBBCargo.setText(bundle.getString("labelBusBCargo"));
        jLabelBBTelefono.setText(bundle.getString("labelBusBTelefono"));
        jLabelBBCodigo.setText(bundle.getString("labelBusBCodigo"));
        jLabelBBFecha.setText(bundle.getString("labelBusBFN"));
        jLabelBBTurno.setText(bundle.getString("labelBusBT"));        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBBBCedula;
    private javax.swing.JLabel jLabelBBApellido;
    private javax.swing.JLabel jLabelBBCargo;
    private javax.swing.JLabel jLabelBBCedula;
    private javax.swing.JLabel jLabelBBCodigo;
    private javax.swing.JLabel jLabelBBFecha;
    private javax.swing.JLabel jLabelBBNombre;
    private javax.swing.JLabel jLabelBBTelefono;
    private javax.swing.JLabel jLabelBBTurno;
    private javax.swing.JLabel jLabelBuscarBibliotecario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBBApellido;
    private javax.swing.JTextField jTextFieldBBCargo;
    private javax.swing.JTextField jTextFieldBBCedula;
    private javax.swing.JTextField jTextFieldBBCodigo;
    private javax.swing.JTextField jTextFieldBBFecha;
    private javax.swing.JTextField jTextFieldBBNombre;
    private javax.swing.JTextField jTextFieldBBTelefono;
    private javax.swing.JTextField jTextFieldBBTurno;
    // End of variables declaration//GEN-END:variables
}
