/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import ec.edu.ups.sistemabiblioteca.enums.Cargo;
import ec.edu.ups.sistemabiblioteca.enums.Turno;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class CrearBibliotecario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearBibliotecario
     */
    public CrearBibliotecario() {
        initComponents();
        
        jComboBoxCargo.removeAllItems();
        jComboBoxTurno.removeAllItems();

        for (Cargo cargo : Cargo.values()) {
            jComboBoxCargo.addItem(cargo.name());
        }

        for (Turno turno : Turno.values()) {
            jComboBoxTurno.addItem(turno.name());
        }
    }

    public JButton getjButtonCBCancelar() {
        return jButtonCBCancelar;
    }

    public void setjButtonCBCancelar(JButton jButtonCBCancelar) {
        this.jButtonCBCancelar = jButtonCBCancelar;
    }

    public JButton getjButtonCBCrear() {
        return jButtonCBCrear;
    }

    public void setjButtonCBCrear(JButton jButtonCBCrear) {
        this.jButtonCBCrear = jButtonCBCrear;
    }

    public JTextField getjTextFieldCBApellido() {
        return jTextFieldCBApellido;
    }

    public void setjTextFieldCBApellido(JTextField jTextFieldCBApellido) {
        this.jTextFieldCBApellido = jTextFieldCBApellido;
    }

    public JTextField getjTextFieldCBCedula() {
        return jTextFieldCBCedula;
    }

    public void setjTextFieldCBCedula(JTextField jTextFieldCBCedula) {
        this.jTextFieldCBCedula = jTextFieldCBCedula;
    }

    public JTextField getjTextFieldCBCodigo() {
        return jTextFieldCBCodigo;
    }

    public void setjTextFieldCBCodigo(JTextField jTextFieldCBCodigo) {
        this.jTextFieldCBCodigo = jTextFieldCBCodigo;
    }

    public JTextField getjTextFieldCBFecha() {
        return jTextFieldCBFecha;
    }

    public void setjTextFieldCBFecha(JTextField jTextFieldCBFecha) {
        this.jTextFieldCBFecha = jTextFieldCBFecha;
    }

    public JTextField getjTextFieldCBNombre() {
        return jTextFieldCBNombre;
    }

    public void setjTextFieldCBNombre(JTextField jTextFieldCBNombre) {
        this.jTextFieldCBNombre = jTextFieldCBNombre;
    }

    public JTextField getjTextFieldCBTelefono() {
        return jTextFieldCBTelefono;
    }

    public void setjTextFieldCBTelefono(JTextField jTextFieldCBTelefono) {
        this.jTextFieldCBTelefono = jTextFieldCBTelefono;
    }

    public JComboBox<String> getjComboBoxCargo() {
        return jComboBoxCargo;
    }

    public void setjComboBoxCargo(JComboBox<String> jComboBoxCargo) {
        this.jComboBoxCargo = jComboBoxCargo;
    }

    public JComboBox<String> getjComboBoxTurno() {
        return jComboBoxTurno;
    }

    public void setjComboBoxTurno(JComboBox<String> jComboBoxTurno) {
        this.jComboBoxTurno = jComboBoxTurno;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);

    }

    public void mostrarInformacion1(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelCrearBibliotecario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelCBCedula = new javax.swing.JLabel();
        jTextFieldCBCedula = new javax.swing.JTextField();
        jLabelCBNombre = new javax.swing.JLabel();
        jTextFieldCBNombre = new javax.swing.JTextField();
        jLabelCBApellido = new javax.swing.JLabel();
        jTextFieldCBApellido = new javax.swing.JTextField();
        jLabelCBCargo = new javax.swing.JLabel();
        jLabelCBTelefono = new javax.swing.JLabel();
        jTextFieldCBTelefono = new javax.swing.JTextField();
        jLabelCBCodBibliotecario = new javax.swing.JLabel();
        jTextFieldCBCodigo = new javax.swing.JTextField();
        jLabelCBFNacimiento = new javax.swing.JLabel();
        jTextFieldCBFecha = new javax.swing.JTextField();
        jLabelCBTurno = new javax.swing.JLabel();
        jButtonCBCrear = new javax.swing.JButton();
        jButtonCBCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jComboBoxTurno = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Bibliotecario");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCrearBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCrearBibliotecario.setText("CREAR UN BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCrearBibliotecario)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelCBCedula.setText("Cedula:");

        jLabelCBNombre.setText("Nombre:");

        jLabelCBApellido.setText("Apellido:");

        jLabelCBCargo.setText("Cargo:");

        jLabelCBTelefono.setText("Telefono:");

        jLabelCBCodBibliotecario.setText("Codigo:");

        jLabelCBFNacimiento.setText("Fecha de Nacimiento:");

        jTextFieldCBFecha.addActionListener(this::jTextFieldCBFechaActionPerformed);

        jLabelCBTurno.setText("Turno:");

        jButtonCBCrear.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCBCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCBCrear.setText("CREAR");
        jButtonCBCrear.addActionListener(this::jButtonCBCrearActionPerformed);

        jButtonCBCancelar.setText("CANCELAR");
        jButtonCBCancelar.addActionListener(this::jButtonCBCancelarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("AAAA-MM-DD");

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCargo.addActionListener(this::jComboBoxCargoActionPerformed);

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCBTelefono)
                    .addComponent(jLabelCBCodBibliotecario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCBFNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabelCBTurno)
                    .addComponent(jLabelCBApellido)
                    .addComponent(jLabelCBCedula)
                    .addComponent(jLabelCBCargo)
                    .addComponent(jLabelCBNombre)
                    .addComponent(jTextFieldCBCedula)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButtonCBCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldCBNombre)
                    .addComponent(jTextFieldCBApellido)
                    .addComponent(jTextFieldCBTelefono)
                    .addComponent(jTextFieldCBCodigo)
                    .addComponent(jTextFieldCBFecha)
                    .addComponent(jComboBoxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCBCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBCodBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCBFNacimiento)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCBCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCBCancelarActionPerformed

    private void jButtonCBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCBCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCBCrearActionPerformed

    private void jTextFieldCBFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCBFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCBFechaActionPerformed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n.mensajes", locale);
        jLabelCrearBibliotecario.setText(bundle.getString("TBlict"));
        jButtonCBCrear.setText(bundle.getString("bttnCrear"));
        jButtonCBCancelar.setText(bundle.getString("bttnCancelar"));
        jLabelCBCedula.setText(bundle.getString("labelCBCedula"));
        jLabelCBNombre.setText(bundle.getString("labelCBNombre"));
        jLabelCBApellido.setText(bundle.getString("labelCBApellido"));
        jLabelCBCargo.setText(bundle.getString("labelCBCargo"));        
        jLabelCBTelefono.setText(bundle.getString("labelCBTelefono"));
        jLabelCBCodBibliotecario.setText(bundle.getString("labelCBCodigo"));       
        jLabelCBFNacimiento.setText(bundle.getString("labelCBFN"));        
        jLabelCBTurno.setText(bundle.getString("labelCBT"));                    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCBCancelar;
    private javax.swing.JButton jButtonCBCrear;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCBApellido;
    private javax.swing.JLabel jLabelCBCargo;
    private javax.swing.JLabel jLabelCBCedula;
    private javax.swing.JLabel jLabelCBCodBibliotecario;
    private javax.swing.JLabel jLabelCBFNacimiento;
    private javax.swing.JLabel jLabelCBNombre;
    private javax.swing.JLabel jLabelCBTelefono;
    private javax.swing.JLabel jLabelCBTurno;
    private javax.swing.JLabel jLabelCrearBibliotecario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCBApellido;
    private javax.swing.JTextField jTextFieldCBCedula;
    private javax.swing.JTextField jTextFieldCBCodigo;
    private javax.swing.JTextField jTextFieldCBFecha;
    private javax.swing.JTextField jTextFieldCBNombre;
    private javax.swing.JTextField jTextFieldCBTelefono;
    // End of variables declaration//GEN-END:variables
}
