/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class CrearBibliotecario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearBibliotecario
     */
    public CrearBibliotecario() {
        initComponents();
    }

    public JButton getjButtonCBCancelar() {
        return jButtonCBCancelar;
    }

    public void setjButtonCBCancelar(JButton jButtonCBCancelar) {
        this.jButtonCBCancelar = jButtonCBCancelar;
    }

    public JButton getjButtonCBCrear() {
        return jButtonCBCrear;
    }

    public void setjButtonCBCrear(JButton jButtonCBCrear) {
        this.jButtonCBCrear = jButtonCBCrear;
    }

    public JTextField getjTextFieldCBApellido() {
        return jTextFieldCBApellido;
    }

    public void setjTextFieldCBApellido(JTextField jTextFieldCBApellido) {
        this.jTextFieldCBApellido = jTextFieldCBApellido;
    }

    public JTextField getjTextFieldCBCargo() {
        return jTextFieldCBCargo;
    }

    public void setjTextFieldCBCargo(JTextField jTextFieldCBCargo) {
        this.jTextFieldCBCargo = jTextFieldCBCargo;
    }

    public JTextField getjTextFieldCBCedula() {
        return jTextFieldCBCedula;
    }

    public void setjTextFieldCBCedula(JTextField jTextFieldCBCedula) {
        this.jTextFieldCBCedula = jTextFieldCBCedula;
    }

    public JTextField getjTextFieldCBCodigo() {
        return jTextFieldCBCodigo;
    }

    public void setjTextFieldCBCodigo(JTextField jTextFieldCBCodigo) {
        this.jTextFieldCBCodigo = jTextFieldCBCodigo;
    }

    public JTextField getjTextFieldCBFecha() {
        return jTextFieldCBFecha;
    }

    public void setjTextFieldCBFecha(JTextField jTextFieldCBFecha) {
        this.jTextFieldCBFecha = jTextFieldCBFecha;
    }

    public JTextField getjTextFieldCBNombre() {
        return jTextFieldCBNombre;
    }

    public void setjTextFieldCBNombre(JTextField jTextFieldCBNombre) {
        this.jTextFieldCBNombre = jTextFieldCBNombre;
    }

    public JTextField getjTextFieldCBTelefono() {
        return jTextFieldCBTelefono;
    }

    public void setjTextFieldCBTelefono(JTextField jTextFieldCBTelefono) {
        this.jTextFieldCBTelefono = jTextFieldCBTelefono;
    }

    public JTextField getjTextFieldCBTurno() {
        return jTextFieldCBTurno;
    }

    public void setjTextFieldCBTurno(JTextField jTextFieldCBTurno) {
        this.jTextFieldCBTurno = jTextFieldCBTurno;
    }
    public void mostrarInformacion(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCBTurno = new javax.swing.JTextField();
        jTextFieldCBCargo = new javax.swing.JTextField();
        jLabelCBTelefono = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelCrearBibliotecario = new javax.swing.JLabel();
        jTextFieldCBTelefono = new javax.swing.JTextField();
        jLabelCBCodBibliotecario = new javax.swing.JLabel();
        jLabelCBCedula = new javax.swing.JLabel();
        jTextFieldCBCodigo = new javax.swing.JTextField();
        jTextFieldCBCedula = new javax.swing.JTextField();
        jLabelCBFNacimiento = new javax.swing.JLabel();
        jLabelCBNombre = new javax.swing.JLabel();
        jTextFieldCBFecha = new javax.swing.JTextField();
        jTextFieldCBNombre = new javax.swing.JTextField();
        jButtonCBCancelar = new javax.swing.JButton();
        jLabelCBApellido = new javax.swing.JLabel();
        jButtonCBCrear = new javax.swing.JButton();
        jTextFieldCBApellido = new javax.swing.JTextField();
        jLabelCBTurno = new javax.swing.JLabel();
        jLabelCBCargo = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Bibliotecario");

        jLabelCBTelefono.setText("Telefono:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCrearBibliotecario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCrearBibliotecario.setText("CREAR UN BIBLIOTECARIO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabelCrearBibliotecario)
                .addGap(24, 24, 24))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearBibliotecario)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabelCBCodBibliotecario.setText("Codigo:");

        jLabelCBCedula.setText("Cedula:");

        jLabelCBFNacimiento.setText("Fecha de Nacimiento:");

        jLabelCBNombre.setText("Nombre:");

        jTextFieldCBFecha.addActionListener(this::jTextFieldCBFechaActionPerformed);

        jButtonCBCancelar.setText("CANCELAR");
        jButtonCBCancelar.addActionListener(this::jButtonCBCancelarActionPerformed);

        jLabelCBApellido.setText("Apellido:");

        jButtonCBCrear.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCBCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCBCrear.setText("CREAR");
        jButtonCBCrear.addActionListener(this::jButtonCBCrearActionPerformed);

        jLabelCBTurno.setText("Turno:");

        jLabelCBCargo.setText("Cargo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelCBTelefono)
                            .addGap(200, 200, 200))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelCBCodBibliotecario)
                            .addGap(208, 208, 208))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelCBFNacimiento)
                            .addGap(135, 135, 135)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCBTurno)
                            .addComponent(jLabelCBApellido)
                            .addComponent(jLabelCBCedula)
                            .addComponent(jLabelCBCargo)
                            .addComponent(jLabelCBNombre)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCBCedula)
                            .addComponent(jTextFieldCBNombre)
                            .addComponent(jTextFieldCBApellido)
                            .addComponent(jTextFieldCBCargo)
                            .addComponent(jTextFieldCBTelefono)
                            .addComponent(jTextFieldCBCodigo)
                            .addComponent(jTextFieldCBFecha)
                            .addComponent(jTextFieldCBTurno))
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButtonCBCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCBCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBCodBibliotecario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBFNacimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCBTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCBTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCBCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCBCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCBCancelarActionPerformed

    private void jButtonCBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCBCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCBCrearActionPerformed

    private void jTextFieldCBFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCBFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCBFechaActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n", locale);
        jLabelCrearBibliotecario.setText(bundle.getString("TBlict"));
        jButtonCBCrear.setText(bundle.getString("bttnCrear"));
        jButtonCBCancelar.setText(bundle.getString("bttnCancelar"));
        jLabelCBCedula.setText(bundle.getString("labelCBCedula"));
        jLabelCBNombre.setText(bundle.getString("labelCBNombre"));
        jLabelCBApellido.setText(bundle.getString("labelCBApellido"));
        jLabelCBCargo.setText(bundle.getString("labelCBCargo"));        
        jLabelCBTelefono.setText(bundle.getString("labelCBTelefono"));
        jLabelCBCodBibliotecario.setText(bundle.getString("labelCBCodigo"));       
        jLabelCBFNacimiento.setText(bundle.getString("labelCBFN "));        
        jLabelCBTurno.setText(bundle.getString("labelCBT"));                    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCBCancelar;
    private javax.swing.JButton jButtonCBCrear;
    private javax.swing.JLabel jLabelCBApellido;
    private javax.swing.JLabel jLabelCBCargo;
    private javax.swing.JLabel jLabelCBCedula;
    private javax.swing.JLabel jLabelCBCodBibliotecario;
    private javax.swing.JLabel jLabelCBFNacimiento;
    private javax.swing.JLabel jLabelCBNombre;
    private javax.swing.JLabel jLabelCBTelefono;
    private javax.swing.JLabel jLabelCBTurno;
    private javax.swing.JLabel jLabelCrearBibliotecario;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldCBApellido;
    private javax.swing.JTextField jTextFieldCBCargo;
    private javax.swing.JTextField jTextFieldCBCedula;
    private javax.swing.JTextField jTextFieldCBCodigo;
    private javax.swing.JTextField jTextFieldCBFecha;
    private javax.swing.JTextField jTextFieldCBNombre;
    private javax.swing.JTextField jTextFieldCBTelefono;
    private javax.swing.JTextField jTextFieldCBTurno;
    // End of variables declaration//GEN-END:variables
}
