/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.bibliotecario;

import ec.edu.ups.sistemabiblioteca.models.Bibliotecario;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ListarBibliotecario extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    /**
     * Creates new form ListarBibliotecario
     */
    public ListarBibliotecario() {
        initComponents();
        construirTabla();
    }

    public JTextField getTxtContadordeBibliotecarios() {
        return txtContadordeBibliotecarios;
    }

    public void setTxtContadordeBibliotecarios(JTextField txtContadordeBibliotecarios) {
        this.txtContadordeBibliotecarios = txtContadordeBibliotecarios;
    }
    

    public JButton getBtnMostrarListaBibliotecarios() {
        return btnMostrarListaBibliotecarios;
    }

    public void setBtnMostrarListaBibliotecarios(JButton btnMostrarListaBibliotecarios) {
        this.btnMostrarListaBibliotecarios = btnMostrarListaBibliotecarios;
    }

    public void construirTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Codigo");
        tblListadoBibliotecarios.setModel(modelo);
    }

    public void cargarDatos(List<Bibliotecario> lista) {

        modelo.setRowCount(0);

        for (Bibliotecario b : lista) {

            Object[] fila = {
                b.getCedula(),
                b.getNombre(),
                b.getApellido(),
                b.getCodigo()
            };
            modelo.addRow(fila);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoBibliotecarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelListaBibliotecarios = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMostrarListaBibliotecarios = new javax.swing.JButton();
        jLabelURListaBibliotecarios = new javax.swing.JLabel();
        txtContadordeBibliotecarios = new javax.swing.JTextField();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista Bibliotecario");

        tblListadoBibliotecarios.setBackground(new java.awt.Color(196, 220, 220));
        tblListadoBibliotecarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoBibliotecarios);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelListaBibliotecarios.setBackground(new java.awt.Color(255, 255, 255));
        jLabelListaBibliotecarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelListaBibliotecarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaBibliotecarios.setText("LISTA DE BIBLIOTECARIOS REGISTRADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListaBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListaBibliotecarios)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        btnMostrarListaBibliotecarios.setBackground(new java.awt.Color(0, 102, 153));
        btnMostrarListaBibliotecarios.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarListaBibliotecarios.setText("Mostrar");

        jLabelURListaBibliotecarios.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelURListaBibliotecarios.setText("Bibliotecarios Registrados");

        txtContadordeBibliotecarios.addActionListener(this::txtContadordeBibliotecariosActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostrarListaBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabelURListaBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContadordeBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarListaBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelURListaBibliotecarios)
                    .addComponent(txtContadordeBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContadordeBibliotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContadordeBibliotecariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadordeBibliotecariosActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n", locale);
        jLabelListaBibliotecarios.setText(bundle.getString("TBliLis"));
        btnMostrarListaBibliotecarios.setText(bundle.getString("bttnMostrar"));
        jLabelURListaBibliotecarios.setText(bundle.getString("labelBR"));
        modelo = new DefaultTableModel();
        modelo.addColumn(bundle.getString("labelLBCedula"));
        modelo.addColumn(bundle.getString("labelLBNombre"));
        modelo.addColumn(bundle.getString("labelLBApellido"));
        modelo.addColumn(bundle.getString("labelLBCargo"));
        tblListadoBibliotecarios.setModel(modelo);   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarListaBibliotecarios;
    private javax.swing.JLabel jLabelListaBibliotecarios;
    private javax.swing.JLabel jLabelURListaBibliotecarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoBibliotecarios;
    private javax.swing.JTextField txtContadordeBibliotecarios;
    // End of variables declaration//GEN-END:variables
}
