/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.usuario;

/**
 *
 * @author Usuario
 */
public class BuscarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarUsuario
     */
    public BuscarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBUDireccion = new javax.swing.JLabel();
        jTextFieldBUCedula = new javax.swing.JTextField();
        jTextFieldBUFNacimiento = new javax.swing.JTextField();
        jTextFieldBUNombre = new javax.swing.JTextField();
        jLabelBUFNacimiento = new javax.swing.JLabel();
        jLabelBUNombre = new javax.swing.JLabel();
        jTextFieldBUApellido = new javax.swing.JTextField();
        jLabelBUApellido = new javax.swing.JLabel();
        jButtonBUBuscar = new javax.swing.JButton();
        jTextFieldBUCElectronico = new javax.swing.JTextField();
        jLabelBUCElectronico = new javax.swing.JLabel();
        jTextFieldBUTelefono = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelBuscarUsuario = new javax.swing.JLabel();
        jLabelBUTelefono = new javax.swing.JLabel();
        jTextFieldBUDireccion = new javax.swing.JTextField();
        jLabelBUCedula = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Usuario");
        setMinimumSize(new java.awt.Dimension(104, 36));
        setPreferredSize(new java.awt.Dimension(348, 500));

        jLabelBUDireccion.setText("Dirección:");

        jTextFieldBUFNacimiento.setEditable(false);

        jTextFieldBUNombre.setEditable(false);

        jLabelBUFNacimiento.setText("Fecha de nacimiento:");

        jLabelBUNombre.setText("Nombre:");

        jTextFieldBUApellido.setEditable(false);

        jLabelBUApellido.setText("Apellido:");

        jButtonBUBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBUBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBUBuscar.setText("BUSCAR");

        jTextFieldBUCElectronico.setEditable(false);

        jLabelBUCElectronico.setText("Correo Electrónico: ");

        jTextFieldBUTelefono.setEditable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelBuscarUsuario.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabelBuscarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscarUsuario.setText("BUSCAR UN USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelBUTelefono.setText("Teléfono:");

        jTextFieldBUDireccion.setEditable(false);
        jTextFieldBUDireccion.addActionListener(this::jTextFieldBUDireccionActionPerformed);

        jLabelBUCedula.setText("Cedula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelBUNombre)
                        .addComponent(jTextFieldBUNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addComponent(jLabelBUCElectronico)
                    .addComponent(jLabelBUApellido)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldBUCElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(jTextFieldBUApellido, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelBUTelefono)
                        .addComponent(jTextFieldBUTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelBUDireccion)
                        .addComponent(jTextFieldBUDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelBUFNacimiento)
                        .addComponent(jTextFieldBUFNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addComponent(jLabelBUCedula)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldBUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jButtonBUBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldBUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBUBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBUApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUCElectronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBUCElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBUTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBUDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBUFNacimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBUFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBUDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBUDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBUDireccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBUBuscar;
    private javax.swing.JLabel jLabelBUApellido;
    private javax.swing.JLabel jLabelBUCElectronico;
    private javax.swing.JLabel jLabelBUCedula;
    private javax.swing.JLabel jLabelBUDireccion;
    private javax.swing.JLabel jLabelBUFNacimiento;
    private javax.swing.JLabel jLabelBUNombre;
    private javax.swing.JLabel jLabelBUTelefono;
    private javax.swing.JLabel jLabelBuscarUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBUApellido;
    private javax.swing.JTextField jTextFieldBUCElectronico;
    private javax.swing.JTextField jTextFieldBUCedula;
    private javax.swing.JTextField jTextFieldBUDireccion;
    private javax.swing.JTextField jTextFieldBUFNacimiento;
    private javax.swing.JTextField jTextFieldBUNombre;
    private javax.swing.JTextField jTextFieldBUTelefono;
    // End of variables declaration//GEN-END:variables
}
