/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.usuario;

/**
 *
 * @author Usuario
 */
public class CrearUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCrearUsuario = new javax.swing.JLabel();
        jLabelCUCedula = new javax.swing.JLabel();
        jTextFieldCUCedula = new javax.swing.JTextField();
        jTextFieldCUNombre = new javax.swing.JTextField();
        jLabelCUNombre = new javax.swing.JLabel();
        jTextFieldCUApellido = new javax.swing.JTextField();
        jLabelCUApellido = new javax.swing.JLabel();
        jTextFieldCUCElectronico = new javax.swing.JTextField();
        jLabelCUCElectronico = new javax.swing.JLabel();
        jTextFieldCUTelefono = new javax.swing.JTextField();
        jLabelCUTelefono = new javax.swing.JLabel();
        jTextFieldCUDireccion = new javax.swing.JTextField();
        jLabelCUDireccion = new javax.swing.JLabel();
        jTextFieldCUFNacimiento = new javax.swing.JTextField();
        jLabelCUFNacimiento = new javax.swing.JLabel();
        jButtonCUCancelar = new javax.swing.JButton();
        jButtonCUCrear = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Usuario");
        setPreferredSize(new java.awt.Dimension(348, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCrearUsuario.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabelCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCrearUsuario.setText("CREE UN NUEVO USUARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelCUCedula.setText("Cedula:");

        jLabelCUNombre.setText("Nombre:");

        jLabelCUApellido.setText("Apellido:");

        jLabelCUCElectronico.setText("Correo Electrónico: ");

        jLabelCUTelefono.setText("Teléfono:");

        jLabelCUDireccion.setText("Dirección:");

        jLabelCUFNacimiento.setText("Fecha de nacimiento:");

        jButtonCUCancelar.setText("CANCELAR");

        jButtonCUCrear.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCUCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCUCrear.setText("CREAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCUFNacimiento)
                            .addComponent(jLabelCUDireccion)
                            .addComponent(jLabelCUTelefono)
                            .addComponent(jLabelCUCElectronico)
                            .addComponent(jLabelCUApellido)
                            .addComponent(jLabelCUNombre)
                            .addComponent(jLabelCUCedula)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCUCedula)
                            .addComponent(jTextFieldCUNombre)
                            .addComponent(jTextFieldCUApellido)
                            .addComponent(jTextFieldCUCElectronico)
                            .addComponent(jTextFieldCUTelefono)
                            .addComponent(jTextFieldCUDireccion)
                            .addComponent(jTextFieldCUFNacimiento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButtonCUCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelCUCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCUNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCUApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCUCElectronico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUCElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCUTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCUDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCUFNacimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCUFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCUCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCUCancelar;
    private javax.swing.JButton jButtonCUCrear;
    private javax.swing.JLabel jLabelCUApellido;
    private javax.swing.JLabel jLabelCUCElectronico;
    private javax.swing.JLabel jLabelCUCedula;
    private javax.swing.JLabel jLabelCUDireccion;
    private javax.swing.JLabel jLabelCUFNacimiento;
    private javax.swing.JLabel jLabelCUNombre;
    private javax.swing.JLabel jLabelCUTelefono;
    private javax.swing.JLabel jLabelCrearUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCUApellido;
    private javax.swing.JTextField jTextFieldCUCElectronico;
    private javax.swing.JTextField jTextFieldCUCedula;
    private javax.swing.JTextField jTextFieldCUDireccion;
    private javax.swing.JTextField jTextFieldCUFNacimiento;
    private javax.swing.JTextField jTextFieldCUNombre;
    private javax.swing.JTextField jTextFieldCUTelefono;
    // End of variables declaration//GEN-END:variables
}
