/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.devolucion;

import ec.edu.ups.sistemabiblioteca.models.Devolucion;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ListarDevolucion extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    /**
     * Creates new form ListarDevolucion
     */
    public ListarDevolucion() {
        initComponents();
        construirTabla();
    }

    public JButton getBtnMostrarListaDevoluciones() {
        return btnMostrarListaDevoluciones;
    }

    public void setBtnMostrarListaDevoluciones(JButton btnMostrarListaDevoluciones) {
        this.btnMostrarListaDevoluciones = btnMostrarListaDevoluciones;
    }

    public JTextField getTxtContadordeDevoluciones() {
        return txtContadordeDevoluciones;
    }

    public void setTxtContadordeDevoluciones(JTextField txtContadordeDevoluciones) {
        this.txtContadordeDevoluciones = txtContadordeDevoluciones;
    }

    public void construirTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Prestamo");
        modelo.addColumn("Isbn");
        modelo.addColumn("Fecha de Devolucion");
        tblListadoDevoluciones.setModel(modelo);
    }

    public void cargarDatos(List<Devolucion> lista) {

        modelo.setRowCount(0);

        for (Devolucion b : lista) {

            Object[] fila = {
                b.getPrestamo(),
                b.getPrestamo().getLibro().getIsbn(),
                b.getFechaDevolucion(),};
            modelo.addRow(fila);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoDevoluciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelListaDevoluciones = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMostrarListaDevoluciones = new javax.swing.JButton();
        jLabelURListaDevoluciones = new javax.swing.JLabel();
        txtContadordeDevoluciones = new javax.swing.JTextField();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista Devolucion");
        setToolTipText("");

        tblListadoDevoluciones.setBackground(new java.awt.Color(196, 220, 220));
        tblListadoDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListadoDevoluciones);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelListaDevoluciones.setBackground(new java.awt.Color(255, 255, 255));
        jLabelListaDevoluciones.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabelListaDevoluciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelListaDevoluciones.setText("LISTA DE DEVOLUCIONES REGISTRADAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListaDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListaDevoluciones)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        btnMostrarListaDevoluciones.setBackground(new java.awt.Color(0, 102, 153));
        btnMostrarListaDevoluciones.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrarListaDevoluciones.setText("Mostrar");

        jLabelURListaDevoluciones.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelURListaDevoluciones.setText("Usuarios Registrados");

        txtContadordeDevoluciones.addActionListener(this::txtContadordeDevolucionesActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostrarListaDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabelURListaDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContadordeDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarListaDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelURListaDevoluciones)
                    .addComponent(txtContadordeDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContadordeDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContadordeDevolucionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadordeDevolucionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarListaDevoluciones;
    private javax.swing.JLabel jLabelListaDevoluciones;
    private javax.swing.JLabel jLabelURListaDevoluciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoDevoluciones;
    private javax.swing.JTextField txtContadordeDevoluciones;
    // End of variables declaration//GEN-END:variables
}
