/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.devolucion;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class RealizarDevolucion extends javax.swing.JInternalFrame {

    /**
     * Creates new form RealizarDevolucion
     */
    public RealizarDevolucion() {
        initComponents();
    }

    public JButton getjButtonBuscarPresamoD() {
        return jButtonBuscarPresamoD;
    }

    public void setjButtonBuscarPresamoD(JButton jButtonBuscarPresamoD) {
        this.jButtonBuscarPresamoD = jButtonBuscarPresamoD;
    }

    public JTextField getjTextFieldDBCodigo() {
        return jTextFieldDBCodigo;
    }

    public void setjTextFieldDBCodigo(JTextField jTextFieldDBCodigo) {
        this.jTextFieldDBCodigo = jTextFieldDBCodigo;
    }

    public JTextField getjTextFieldDCodigo() {
        return jTextFieldDCodigo;
    }

    public void setjTextFieldDCodigo(JTextField jTextFieldDCodigo) {
        this.jTextFieldDCodigo = jTextFieldDCodigo;
    }

    public JTextField getjTextFieldDFLimite() {
        return jTextFieldDFLimite;
    }

    public void setjTextFieldDFLimite(JTextField jTextFieldDFLimite) {
        this.jTextFieldDFLimite = jTextFieldDFLimite;
    }

    public JTextField getjTextFieldDFPrestamo() {
        return jTextFieldDFPrestamo;
    }

    public void setjTextFieldDFPrestamo(JTextField jTextFieldDFPrestamo) {
        this.jTextFieldDFPrestamo = jTextFieldDFPrestamo;
    }

    public JTextField getjTextFieldDISBNLibro() {
        return jTextFieldDISBNLibro;
    }

    public void setjTextFieldDISBNLibro(JTextField jTextFieldDISBNLibro) {
        this.jTextFieldDISBNLibro = jTextFieldDISBNLibro;
    }

    public JTextField getjTextFieldDTLibro() {
        return jTextFieldDTLibro;
    }

    public void setjTextFieldDTLibro(JTextField jTextFieldDTLibro) {
        this.jTextFieldDTLibro = jTextFieldDTLibro;
    }

    public JTextField getjTextFieldDUCedula() {
        return jTextFieldDUCedula;
    }

    public void setjTextFieldDUCedula(JTextField jTextFieldDUCedula) {
        this.jTextFieldDUCedula = jTextFieldDUCedula;
    }

    public JTextField getjTextFieldDUNombre() {
        return jTextFieldDUNombre;
    }

    public void setjTextFieldDUNombre(JTextField jTextFieldDUNombre) {
        this.jTextFieldDUNombre = jTextFieldDUNombre;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDBCodigo = new javax.swing.JTextField();
        jLabelDISBNLibro = new javax.swing.JLabel();
        jTextFieldDFLimite = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldDFPrestamo = new javax.swing.JTextField();
        jTextFieldDISBNLibro = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelDevolucion = new javax.swing.JLabel();
        jLabelDFPrestamo = new javax.swing.JLabel();
        jTextFieldDUNombre = new javax.swing.JTextField();
        jLabelDCodigo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelDNUsuario = new javax.swing.JLabel();
        jTextFieldDCodigo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDCUsuario = new javax.swing.JLabel();
        jTextFieldDTLibro = new javax.swing.JTextField();
        jLabelDTLibro = new javax.swing.JLabel();
        jTextFieldDUCedula = new javax.swing.JTextField();
        jLabelDBCodigo = new javax.swing.JLabel();
        jButtonBuscarPresamoD = new javax.swing.JButton();
        jLabelDFDevolucion = new javax.swing.JLabel();

        jTextFieldDBCodigo.setEditable(false);
        jTextFieldDBCodigo.addActionListener(this::jTextFieldDBCodigoActionPerformed);

        jLabelDISBNLibro.setText("Libro(ISBN):");

        jTextFieldDFPrestamo.setEditable(false);
        jTextFieldDFPrestamo.addActionListener(this::jTextFieldDFPrestamoActionPerformed);

        jTextFieldDISBNLibro.setEditable(false);
        jTextFieldDISBNLibro.addActionListener(this::jTextFieldDISBNLibroActionPerformed);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDevolucion.setText("DEVOLVOLUCION DE LIBRO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelDevolucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDevolucion)
                .addGap(15, 15, 15))
        );

        jLabelDFPrestamo.setText("Fecha prestamo:");

        jTextFieldDUNombre.setEditable(false);

        jLabelDCodigo.setText("Codigo del Prestamo:");

        jLabelDNUsuario.setText("Nombre:");

        jTextFieldDCodigo.addActionListener(this::jTextFieldDCodigoActionPerformed);

        jLabelDCUsuario.setText("Usuario(Cedula):");

        jTextFieldDTLibro.setEditable(false);
        jTextFieldDTLibro.addActionListener(this::jTextFieldDTLibroActionPerformed);

        jLabelDTLibro.setText("Titulo:");

        jTextFieldDUCedula.setEditable(false);

        jLabelDBCodigo.setText("Bibliotecario(Codigo):");

        jButtonBuscarPresamoD.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBuscarPresamoD.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarPresamoD.setText("BUSCAR");
        jButtonBuscarPresamoD.addActionListener(this::jButtonBuscarPresamoDActionPerformed);

        jLabelDFDevolucion.setText("Fecha Devolucion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDTLibro)
                            .addComponent(jLabelDISBNLibro))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDTLibro)
                            .addComponent(jTextFieldDISBNLibro)))
                    .addComponent(jSeparator1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDFPrestamo)
                            .addComponent(jLabelDFDevolucion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDFPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jTextFieldDFLimite)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDCUsuario)
                            .addComponent(jLabelDNUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDUNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jTextFieldDUCedula)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDBCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarPresamoD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDCodigo)
                    .addComponent(jTextFieldDCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPresamoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDCUsuario)
                    .addComponent(jTextFieldDUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDNUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDISBNLibro)
                    .addComponent(jTextFieldDISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDTLibro)
                    .addComponent(jTextFieldDTLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDBCodigo)
                    .addComponent(jTextFieldDBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDFPrestamo)
                    .addComponent(jTextFieldDFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDFDevolucion)
                    .addComponent(jTextFieldDFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDBCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDBCodigoActionPerformed

    private void jTextFieldDFPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDFPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDFPrestamoActionPerformed

    private void jTextFieldDISBNLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDISBNLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDISBNLibroActionPerformed

    private void jTextFieldDCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDCodigoActionPerformed

    private void jTextFieldDTLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDTLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDTLibroActionPerformed

    private void jButtonBuscarPresamoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPresamoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPresamoDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPresamoD;
    private javax.swing.JLabel jLabelDBCodigo;
    private javax.swing.JLabel jLabelDCUsuario;
    private javax.swing.JLabel jLabelDCodigo;
    private javax.swing.JLabel jLabelDFDevolucion;
    private javax.swing.JLabel jLabelDFPrestamo;
    private javax.swing.JLabel jLabelDISBNLibro;
    private javax.swing.JLabel jLabelDNUsuario;
    private javax.swing.JLabel jLabelDTLibro;
    private javax.swing.JLabel jLabelDevolucion;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldDBCodigo;
    private javax.swing.JTextField jTextFieldDCodigo;
    private javax.swing.JTextField jTextFieldDFLimite;
    private javax.swing.JTextField jTextFieldDFPrestamo;
    private javax.swing.JTextField jTextFieldDISBNLibro;
    private javax.swing.JTextField jTextFieldDTLibro;
    private javax.swing.JTextField jTextFieldDUCedula;
    private javax.swing.JTextField jTextFieldDUNombre;
    // End of variables declaration//GEN-END:variables
}
