/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.prestamo;

/**
 *
 * @author Usuario
 */
public class BuscarPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPrestamo
     */
    public BuscarPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBPFPrestamo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelBuscarPrestamo = new javax.swing.JLabel();
        jTextFieldBPISBNLibro = new javax.swing.JTextField();
        jTextFieldBPFLimite = new javax.swing.JTextField();
        jLabelBPISBNLibro = new javax.swing.JLabel();
        jTextFieldBPBCodigo = new javax.swing.JTextField();
        jLabelBPFDevolucion = new javax.swing.JLabel();
        jButtonBuscarPresamo = new javax.swing.JButton();
        jLabelBPBCodigo = new javax.swing.JLabel();
        jTextFieldBPUCedula = new javax.swing.JTextField();
        jLabelBPTLibro = new javax.swing.JLabel();
        jTextFieldBPTLibro = new javax.swing.JTextField();
        jLabelBPCUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldBPCodigo = new javax.swing.JTextField();
        jLabelBPNUsuario = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelBPCodigo = new javax.swing.JLabel();
        jTextFieldBPUNombre = new javax.swing.JTextField();
        jTextFieldBPFPrestamo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Prestamo");
        setToolTipText("");

        jLabelBPFPrestamo.setText("Fecha prestamo:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBuscarPrestamo.setText("BUSCAR UN PRESTAMO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelBuscarPrestamo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarPrestamo)
                .addGap(15, 15, 15))
        );

        jTextFieldBPISBNLibro.setEditable(false);
        jTextFieldBPISBNLibro.addActionListener(this::jTextFieldBPISBNLibroActionPerformed);

        jTextFieldBPFLimite.setEditable(false);

        jLabelBPISBNLibro.setText("Libro(ISBN):");

        jTextFieldBPBCodigo.setEditable(false);
        jTextFieldBPBCodigo.addActionListener(this::jTextFieldBPBCodigoActionPerformed);

        jLabelBPFDevolucion.setText("Fecha Limite:");

        jButtonBuscarPresamo.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBuscarPresamo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarPresamo.setText("BUSCAR");
        jButtonBuscarPresamo.addActionListener(this::jButtonBuscarPresamoActionPerformed);

        jLabelBPBCodigo.setText("Bibliotecario(Codigo):");

        jTextFieldBPUCedula.setEditable(false);

        jLabelBPTLibro.setText("Titulo:");

        jTextFieldBPTLibro.setEditable(false);
        jTextFieldBPTLibro.addActionListener(this::jTextFieldBPTLibroActionPerformed);

        jLabelBPCUsuario.setText("Usuario(Cedula):");

        jTextFieldBPCodigo.addActionListener(this::jTextFieldBPCodigoActionPerformed);

        jLabelBPNUsuario.setText("Nombre:");

        jLabelBPCodigo.setText("Codigo del Prestamo:");

        jTextFieldBPUNombre.setEditable(false);

        jTextFieldBPFPrestamo.setEditable(false);
        jTextFieldBPFPrestamo.addActionListener(this::jTextFieldBPFPrestamoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBPTLibro)
                            .addComponent(jLabelBPISBNLibro))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBPTLibro)
                            .addComponent(jTextFieldBPISBNLibro)))
                    .addComponent(jSeparator1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBPFPrestamo)
                            .addComponent(jLabelBPFDevolucion))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBPFPrestamo)
                            .addComponent(jTextFieldBPFLimite)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBPCUsuario)
                            .addComponent(jLabelBPNUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBPUNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jTextFieldBPUCedula)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBPBCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBPCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarPresamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPCodigo)
                    .addComponent(jTextFieldBPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPresamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPCUsuario)
                    .addComponent(jTextFieldBPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBPUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBPNUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPISBNLibro)
                    .addComponent(jTextFieldBPISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPTLibro)
                    .addComponent(jTextFieldBPTLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPBCodigo)
                    .addComponent(jTextFieldBPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPFPrestamo)
                    .addComponent(jTextFieldBPFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPFDevolucion)
                    .addComponent(jTextFieldBPFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBPISBNLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPISBNLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPISBNLibroActionPerformed

    private void jTextFieldBPBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPBCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPBCodigoActionPerformed

    private void jButtonBuscarPresamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPresamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPresamoActionPerformed

    private void jTextFieldBPTLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPTLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPTLibroActionPerformed

    private void jTextFieldBPCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPCodigoActionPerformed

    private void jTextFieldBPFPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPFPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPFPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarPresamo;
    private javax.swing.JLabel jLabelBPBCodigo;
    private javax.swing.JLabel jLabelBPCUsuario;
    private javax.swing.JLabel jLabelBPCodigo;
    private javax.swing.JLabel jLabelBPFDevolucion;
    private javax.swing.JLabel jLabelBPFPrestamo;
    private javax.swing.JLabel jLabelBPISBNLibro;
    private javax.swing.JLabel jLabelBPNUsuario;
    private javax.swing.JLabel jLabelBPTLibro;
    private javax.swing.JLabel jLabelBuscarPrestamo;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldBPBCodigo;
    private javax.swing.JTextField jTextFieldBPCodigo;
    private javax.swing.JTextField jTextFieldBPFLimite;
    private javax.swing.JTextField jTextFieldBPFPrestamo;
    private javax.swing.JTextField jTextFieldBPISBNLibro;
    private javax.swing.JTextField jTextFieldBPTLibro;
    private javax.swing.JTextField jTextFieldBPUCedula;
    private javax.swing.JTextField jTextFieldBPUNombre;
    // End of variables declaration//GEN-END:variables
}
