/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.prestamo;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class BuscarPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarPrestamo
     */
    public BuscarPrestamo() {
        initComponents();
    }

    public JButton getjButtonBuscarPresamo() {
        return jButtonBuscarPresamo;
    }

    public void setjButtonBuscarPresamo(JButton jButtonBuscarPresamo) {
        this.jButtonBuscarPresamo = jButtonBuscarPresamo;
    }

    public JTextField getjTextFieldBPBCodigo() {
        return jTextFieldBPBCodigo;
    }

    public void setjTextFieldBPBCodigo(JTextField jTextFieldBPBCodigo) {
        this.jTextFieldBPBCodigo = jTextFieldBPBCodigo;
    }

    public JTextField getjTextFieldBPCodigo() {
        return jTextFieldBPCodigo;
    }

    public void setjTextFieldBPCodigo(JTextField jTextFieldBPCodigo) {
        this.jTextFieldBPCodigo = jTextFieldBPCodigo;
    }

    public JTextField getjTextFieldBPFLimite() {
        return jTextFieldBPFLimite;
    }

    public void setjTextFieldBPFLimite(JTextField jTextFieldBPFLimite) {
        this.jTextFieldBPFLimite = jTextFieldBPFLimite;
    }

    public JTextField getjTextFieldBPFPrestamo() {
        return jTextFieldBPFPrestamo;
    }

    public void setjTextFieldBPFPrestamo(JTextField jTextFieldBPFPrestamo) {
        this.jTextFieldBPFPrestamo = jTextFieldBPFPrestamo;
    }

    public JTextField getjTextFieldBPISBNLibro() {
        return jTextFieldBPISBNLibro;
    }

    public void setjTextFieldBPISBNLibro(JTextField jTextFieldBPISBNLibro) {
        this.jTextFieldBPISBNLibro = jTextFieldBPISBNLibro;
    }

    public JTextField getjTextFieldBPTLibro() {
        return jTextFieldBPTLibro;
    }

    public void setjTextFieldBPTLibro(JTextField jTextFieldBPTLibro) {
        this.jTextFieldBPTLibro = jTextFieldBPTLibro;
    }

    public JTextField getjTextFieldBPUCedula() {
        return jTextFieldBPUCedula;
    }

    public void setjTextFieldBPUCedula(JTextField jTextFieldBPUCedula) {
        this.jTextFieldBPUCedula = jTextFieldBPUCedula;
    }

    public JTextField getjTextFieldBPUNombre() {
        return jTextFieldBPUNombre;
    }

    public void setjTextFieldBPUNombre(JTextField jTextFieldBPUNombre) {
        this.jTextFieldBPUNombre = jTextFieldBPUNombre;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelBuscarPrestamo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonBuscarPresamo = new javax.swing.JButton();
        jLabelBPFDevolucion = new javax.swing.JLabel();
        jLabelBPISBNLibro = new javax.swing.JLabel();
        jTextFieldBPCodigo = new javax.swing.JTextField();
        jTextFieldBPFLimite = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldBPISBNLibro = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelBPCUsuario = new javax.swing.JLabel();
        jTextFieldBPTLibro = new javax.swing.JTextField();
        jLabelBPFPrestamo = new javax.swing.JLabel();
        jLabelBPTLibro = new javax.swing.JLabel();
        jTextFieldBPUCedula = new javax.swing.JTextField();
        jLabelBPBCodigo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldBPFPrestamo = new javax.swing.JTextField();
        jTextFieldBPUNombre = new javax.swing.JTextField();
        jLabelBPCodigo = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldBPBCodigo = new javax.swing.JTextField();
        jLabelBPNUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Prestamo");
        setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelBuscarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBuscarPrestamo.setText("BUSCAR UN PRESTAMO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBuscarPrestamo)
                .addGap(72, 72, 72))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBuscarPrestamo)
                .addGap(15, 15, 15))
        );

        jButtonBuscarPresamo.setBackground(new java.awt.Color(0, 102, 153));
        jButtonBuscarPresamo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscarPresamo.setText("BUSCAR");
        jButtonBuscarPresamo.addActionListener(this::jButtonBuscarPresamoActionPerformed);

        jLabelBPFDevolucion.setText("Fecha Limite:");

        jLabelBPISBNLibro.setText("Libro(ISBN):");

        jTextFieldBPCodigo.addActionListener(this::jTextFieldBPCodigoActionPerformed);

        jTextFieldBPFLimite.setEditable(false);

        jTextFieldBPISBNLibro.setEditable(false);
        jTextFieldBPISBNLibro.addActionListener(this::jTextFieldBPISBNLibroActionPerformed);

        jLabelBPCUsuario.setText("Usuario(Cedula):");

        jTextFieldBPTLibro.setEditable(false);
        jTextFieldBPTLibro.addActionListener(this::jTextFieldBPTLibroActionPerformed);

        jLabelBPFPrestamo.setText("Fecha prestamo:");

        jLabelBPTLibro.setText("Titulo:");

        jTextFieldBPUCedula.setEditable(false);

        jLabelBPBCodigo.setText("Bibliotecario(Codigo):");

        jTextFieldBPFPrestamo.setEditable(false);
        jTextFieldBPFPrestamo.addActionListener(this::jTextFieldBPFPrestamoActionPerformed);

        jTextFieldBPUNombre.setEditable(false);

        jLabelBPCodigo.setText("Codigo del Prestamo:");

        jTextFieldBPBCodigo.setEditable(false);
        jTextFieldBPBCodigo.addActionListener(this::jTextFieldBPBCodigoActionPerformed);

        jLabelBPNUsuario.setText("Nombre:");

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBPTLibro)
                            .addComponent(jLabelBPISBNLibro))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBPTLibro)
                            .addComponent(jTextFieldBPISBNLibro)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBPFPrestamo)
                            .addComponent(jLabelBPFDevolucion))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBPFPrestamo)
                            .addComponent(jTextFieldBPFLimite)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBPCUsuario)
                            .addComponent(jLabelBPNUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBPUNombre)
                            .addComponent(jTextFieldBPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBPBCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBPCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarPresamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPCodigo)
                    .addComponent(jTextFieldBPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarPresamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPCUsuario)
                    .addComponent(jTextFieldBPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBPUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBPNUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPISBNLibro)
                    .addComponent(jTextFieldBPISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPTLibro)
                    .addComponent(jTextFieldBPTLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPBCodigo)
                    .addComponent(jTextFieldBPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPFPrestamo)
                    .addComponent(jTextFieldBPFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBPFDevolucion)
                    .addComponent(jTextFieldBPFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBPISBNLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPISBNLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPISBNLibroActionPerformed

    private void jTextFieldBPBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPBCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPBCodigoActionPerformed

    private void jButtonBuscarPresamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPresamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPresamoActionPerformed

    private void jTextFieldBPTLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPTLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPTLibroActionPerformed

    private void jTextFieldBPCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPCodigoActionPerformed

    private void jTextFieldBPFPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBPFPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBPFPrestamoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n", locale);
        jLabelBuscarPrestamo.setText(bundle.getString("TPbs"));
        jButtonBuscarPresamo.setText(bundle.getString("bttnBuscar"));
        jLabelBPCodigo.setText(bundle.getString("labelPCodigo"));
        jLabelBPCUsuario.setText(bundle.getString("labelPUsuario"));        
        jLabelBPNUsuario.setText(bundle.getString("labelPNombre"));
        jLabelBPISBNLibro.setText(bundle.getString("labelPLibro"));
        jLabelBPTLibro.setText(bundle.getString("labelPTitulo"));
        jLabelBPBCodigo.setText(bundle.getString("labelPBLc"));
                
                
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarPresamo;
    private javax.swing.JLabel jLabelBPBCodigo;
    private javax.swing.JLabel jLabelBPCUsuario;
    private javax.swing.JLabel jLabelBPCodigo;
    private javax.swing.JLabel jLabelBPFDevolucion;
    private javax.swing.JLabel jLabelBPFPrestamo;
    private javax.swing.JLabel jLabelBPISBNLibro;
    private javax.swing.JLabel jLabelBPNUsuario;
    private javax.swing.JLabel jLabelBPTLibro;
    private javax.swing.JLabel jLabelBuscarPrestamo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldBPBCodigo;
    private javax.swing.JTextField jTextFieldBPCodigo;
    private javax.swing.JTextField jTextFieldBPFLimite;
    private javax.swing.JTextField jTextFieldBPFPrestamo;
    private javax.swing.JTextField jTextFieldBPISBNLibro;
    private javax.swing.JTextField jTextFieldBPTLibro;
    private javax.swing.JTextField jTextFieldBPUCedula;
    private javax.swing.JTextField jTextFieldBPUNombre;
    // End of variables declaration//GEN-END:variables
}
