/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.prestamo;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class CrearPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearPrestamo
     */
    public CrearPrestamo() {
        initComponents();
    }

    public JButton getjButtonCPCancelar() {
        return jButtonCPCancelar;
    }

    public void setjButtonCPCancelar(JButton jButtonCPCancelar) {
        this.jButtonCPCancelar = jButtonCPCancelar;
    }

    public JButton getjButtonCPCrear() {
        return jButtonCPCrear;
    }

    public void setjButtonCPCrear(JButton jButtonCPCrear) {
        this.jButtonCPCrear = jButtonCPCrear;
    }

    public JButton getjButtonCPLBuscar() {
        return jButtonCPLBuscar;
    }

    public void setjButtonCPLBuscar(JButton jButtonCPLBuscar) {
        this.jButtonCPLBuscar = jButtonCPLBuscar;
    }

    public JButton getjButtonCPUBuscar() {
        return jButtonCPUBuscar;
    }

    public void setjButtonCPUBuscar(JButton jButtonCPUBuscar) {
        this.jButtonCPUBuscar = jButtonCPUBuscar;
    }

    public JTextField getjTextFieldCPBCodigo() {
        return jTextFieldCPBCodigo;
    }

    public void setjTextFieldCPBCodigo(JTextField jTextFieldCPBCodigo) {
        this.jTextFieldCPBCodigo = jTextFieldCPBCodigo;
    }

    public JTextField getjTextFieldCPCodigo() {
        return jTextFieldCPCodigo;
    }

    public void setjTextFieldCPCodigo(JTextField jTextFieldCPCodigo) {
        this.jTextFieldCPCodigo = jTextFieldCPCodigo;
    }

    public JTextField getjTextFieldCPFLimite() {
        return jTextFieldCPFLimite;
    }

    public void setjTextFieldCPFLimite(JTextField jTextFieldCPFLimite) {
        this.jTextFieldCPFLimite = jTextFieldCPFLimite;
    }

    public JTextField getjTextFieldCPFPrestamo() {
        return jTextFieldCPFPrestamo;
    }

    public void setjTextFieldCPFPrestamo(JTextField jTextFieldCPFPrestamo) {
        this.jTextFieldCPFPrestamo = jTextFieldCPFPrestamo;
    }

    public JTextField getjTextFieldCPISBNLibro() {
        return jTextFieldCPISBNLibro;
    }

    public void setjTextFieldCPISBNLibro(JTextField jTextFieldCPISBNLibro) {
        this.jTextFieldCPISBNLibro = jTextFieldCPISBNLibro;
    }

    public JTextField getjTextFieldCPTLibro() {
        return jTextFieldCPTLibro;
    }

    public void setjTextFieldCPTLibro(JTextField jTextFieldCPTLibro) {
        this.jTextFieldCPTLibro = jTextFieldCPTLibro;
    }

    public JTextField getjTextFieldCPUCedula() {
        return jTextFieldCPUCedula;
    }

    public void setjTextFieldCPUCedula(JTextField jTextFieldCPUCedula) {
        this.jTextFieldCPUCedula = jTextFieldCPUCedula;
    }

    public JTextField getjTextFieldCPUNombre() {
        return jTextFieldCPUNombre;
    }

    public void setjTextFieldCPUNombre(JTextField jTextFieldCPUNombre) {
        this.jTextFieldCPUNombre = jTextFieldCPUNombre;
    }

    public void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);

    }

    public void mostrarInformacion1(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabelCrearPrestamo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldCPISBNLibro = new javax.swing.JTextField();
        jLabelCPFPrestamo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldCPFPrestamo = new javax.swing.JTextField();
        jTextFieldCPUNombre = new javax.swing.JTextField();
        jLabelCPCodigo = new javax.swing.JLabel();
        jLabelCPNUsuario = new javax.swing.JLabel();
        jTextFieldCPCodigo = new javax.swing.JTextField();
        jButtonCPLBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCPUBuscar = new javax.swing.JButton();
        jLabelCPCUsuario = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonCPCancelar = new javax.swing.JButton();
        jTextFieldCPTLibro = new javax.swing.JTextField();
        jTextFieldCPUCedula = new javax.swing.JTextField();
        jLabelCPBCodigo = new javax.swing.JLabel();
        jButtonCPCrear = new javax.swing.JButton();
        jLabelCPFDevolucion = new javax.swing.JLabel();
        jTextFieldCPBCodigo = new javax.swing.JTextField();
        jLabelCPISBNLibro = new javax.swing.JLabel();
        jTextFieldCPFLimite = new javax.swing.JTextField();
        jLabelCPTLibro = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Prestamo");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCrearPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCrearPrestamo.setText("CREAR UN PRESTAMO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelCrearPrestamo)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearPrestamo)
                .addGap(15, 15, 15))
        );

        jTextFieldCPISBNLibro.addActionListener(this::jTextFieldCPISBNLibroActionPerformed);

        jLabelCPFPrestamo.setText("Fecha prestamo:");

        jTextFieldCPFPrestamo.addActionListener(this::jTextFieldCPFPrestamoActionPerformed);

        jTextFieldCPUNombre.setEditable(false);

        jLabelCPCodigo.setText("Codigo del Prestamo:");

        jLabelCPNUsuario.setText("Nombre:");

        jTextFieldCPCodigo.addActionListener(this::jTextFieldCPCodigoActionPerformed);

        jButtonCPLBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCPLBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCPLBuscar.setText("BUSCAR");
        jButtonCPLBuscar.addActionListener(this::jButtonCPLBuscarActionPerformed);

        jButtonCPUBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCPUBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCPUBuscar.setText("BUSCAR");
        jButtonCPUBuscar.addActionListener(this::jButtonCPUBuscarActionPerformed);

        jLabelCPCUsuario.setText("Usuario(Cedula):");

        jButtonCPCancelar.setText("Cancelar");
        jButtonCPCancelar.addActionListener(this::jButtonCPCancelarActionPerformed);

        jTextFieldCPTLibro.setEditable(false);
        jTextFieldCPTLibro.addActionListener(this::jTextFieldCPTLibroActionPerformed);

        jLabelCPBCodigo.setText("Bibliotecario(Cedula):");

        jButtonCPCrear.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCPCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCPCrear.setText("CREAR");
        jButtonCPCrear.addActionListener(this::jButtonCPCrearActionPerformed);

        jLabelCPFDevolucion.setText("Fecha Limite:");

        jTextFieldCPBCodigo.addActionListener(this::jTextFieldCPBCodigoActionPerformed);

        jLabelCPISBNLibro.setText("Libro(ISBN):");

        jLabelCPTLibro.setText("Titulo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonCPCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCPCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCPTLibro)
                                .addComponent(jLabelCPISBNLibro))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCPTLibro)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldCPISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonCPLBuscar))))
                        .addComponent(jSeparator1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCPCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCPCodigo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCPFPrestamo)
                                .addComponent(jLabelCPFDevolucion))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCPFPrestamo)
                                .addComponent(jTextFieldCPFLimite)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCPCUsuario)
                                .addComponent(jLabelCPNUsuario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextFieldCPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonCPUBuscar))
                                .addComponent(jTextFieldCPUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCPBCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPCodigo)
                    .addComponent(jTextFieldCPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPCUsuario)
                    .addComponent(jTextFieldCPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCPUBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPNUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPISBNLibro)
                    .addComponent(jTextFieldCPISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCPLBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPTLibro)
                    .addComponent(jTextFieldCPTLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPBCodigo)
                    .addComponent(jTextFieldCPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPFPrestamo)
                    .addComponent(jTextFieldCPFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPFDevolucion)
                    .addComponent(jTextFieldCPFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCPCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCPCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCPCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCPCrearActionPerformed

    private void jButtonCPCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCPCancelarActionPerformed

    private void jTextFieldCPTLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPTLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPTLibroActionPerformed

    private void jTextFieldCPISBNLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPISBNLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPISBNLibroActionPerformed

    private void jTextFieldCPFPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFPrestamoActionPerformed

    private void jTextFieldCPBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPBCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPBCodigoActionPerformed

    private void jButtonCPUBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPUBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCPUBuscarActionPerformed

    private void jButtonCPLBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPLBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCPLBuscarActionPerformed

    private void jTextFieldCPCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPCodigoActionPerformed

    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle =ResourceBundle.getBundle("ec.edu.ups.sistemabiblioteca.i18n", locale);
        jLabelCrearPrestamo.setText(bundle.getString("TPcp"));
        jButtonCPUBuscar.setText(bundle.getString("TPbs"));
        jButtonCPLBuscar.setText(bundle.getString("TPbs"));
        jLabelCPCodigo.setText(bundle.getString("labelCPCodigo"));       
        jLabelCPCUsuario.setText(bundle.getString("labelCPUsuario"));        
        jLabelCPNUsuario.setText(bundle.getString("labelCPNombre"));      
        jLabelCPISBNLibro.setText(bundle.getString("labelCPLibro"));
        jLabelCPTLibro.setText(bundle.getString("labelCPTitulo"));
        jLabelCPBCodigo.setText(bundle.getString("labelCPBLc"));
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCPCancelar;
    private javax.swing.JButton jButtonCPCrear;
    private javax.swing.JButton jButtonCPLBuscar;
    private javax.swing.JButton jButtonCPUBuscar;
    private javax.swing.JLabel jLabelCPBCodigo;
    private javax.swing.JLabel jLabelCPCUsuario;
    private javax.swing.JLabel jLabelCPCodigo;
    private javax.swing.JLabel jLabelCPFDevolucion;
    private javax.swing.JLabel jLabelCPFPrestamo;
    private javax.swing.JLabel jLabelCPISBNLibro;
    private javax.swing.JLabel jLabelCPNUsuario;
    private javax.swing.JLabel jLabelCPTLibro;
    private javax.swing.JLabel jLabelCrearPrestamo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldCPBCodigo;
    private javax.swing.JTextField jTextFieldCPCodigo;
    private javax.swing.JTextField jTextFieldCPFLimite;
    private javax.swing.JTextField jTextFieldCPFPrestamo;
    private javax.swing.JTextField jTextFieldCPISBNLibro;
    private javax.swing.JTextField jTextFieldCPTLibro;
    private javax.swing.JTextField jTextFieldCPUCedula;
    private javax.swing.JTextField jTextFieldCPUNombre;
    // End of variables declaration//GEN-END:variables
}
