/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.view.prestamo;

/**
 *
 * @author Usuario
 */
public class CrearPrestamo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearPrestamo
     */
    public CrearPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCPTLibro = new javax.swing.JLabel();
        jLabelCPCUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldCPCodigo = new javax.swing.JTextField();
        jLabelCPNUsuario = new javax.swing.JLabel();
        jLabelCPCodigo = new javax.swing.JLabel();
        jTextFieldCPUNombre = new javax.swing.JTextField();
        jTextFieldCPFPrestamo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelCPFPrestamo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelCrearPrestamo = new javax.swing.JLabel();
        jTextFieldCPISBNLibro = new javax.swing.JTextField();
        jTextFieldCPFLimite = new javax.swing.JTextField();
        jLabelCPISBNLibro = new javax.swing.JLabel();
        jTextFieldCPBCodigo = new javax.swing.JTextField();
        jLabelCPFDevolucion = new javax.swing.JLabel();
        jButtonCPCrear = new javax.swing.JButton();
        jLabelCPBCodigo = new javax.swing.JLabel();
        jTextFieldCPUCedula = new javax.swing.JTextField();
        jTextFieldCPTLibro = new javax.swing.JTextField();
        jButtonCPCancelar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonCPUBuscar = new javax.swing.JButton();
        jButtonCPLBuscar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Prestamo");

        jLabelCPTLibro.setText("Titulo:");

        jLabelCPCUsuario.setText("Usuario(Cedula):");

        jTextFieldCPCodigo.addActionListener(this::jTextFieldCPCodigoActionPerformed);

        jLabelCPNUsuario.setText("Nombre:");

        jLabelCPCodigo.setText("Codigo del Prestamo:");

        jTextFieldCPUNombre.setEditable(false);

        jTextFieldCPFPrestamo.addActionListener(this::jTextFieldCPFPrestamoActionPerformed);

        jLabelCPFPrestamo.setText("Fecha prestamo:");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabelCrearPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCrearPrestamo.setText("CREAR UN PRESTAMO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCrearPrestamo)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCrearPrestamo)
                .addGap(15, 15, 15))
        );

        jTextFieldCPISBNLibro.addActionListener(this::jTextFieldCPISBNLibroActionPerformed);

        jLabelCPISBNLibro.setText("Libro(ISBN):");

        jTextFieldCPBCodigo.addActionListener(this::jTextFieldCPBCodigoActionPerformed);

        jLabelCPFDevolucion.setText("Fecha Limite:");

        jButtonCPCrear.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCPCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCPCrear.setText("CREAR");
        jButtonCPCrear.addActionListener(this::jButtonCPCrearActionPerformed);

        jLabelCPBCodigo.setText("Bibliotecario(Codigo):");

        jTextFieldCPTLibro.setEditable(false);
        jTextFieldCPTLibro.addActionListener(this::jTextFieldCPTLibroActionPerformed);

        jButtonCPCancelar.setText("Cancelar");
        jButtonCPCancelar.addActionListener(this::jButtonCPCancelarActionPerformed);

        jButtonCPUBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCPUBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCPUBuscar.setText("BUSCAR");
        jButtonCPUBuscar.addActionListener(this::jButtonCPUBuscarActionPerformed);

        jButtonCPLBuscar.setBackground(new java.awt.Color(0, 102, 153));
        jButtonCPLBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCPLBuscar.setText("BUSCAR");
        jButtonCPLBuscar.addActionListener(this::jButtonCPLBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonCPCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCPCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCPTLibro)
                                .addComponent(jLabelCPISBNLibro))
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCPTLibro)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldCPISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonCPLBuscar))))
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelCPCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCPCodigo))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCPFPrestamo)
                                .addComponent(jLabelCPFDevolucion))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCPFPrestamo)
                                .addComponent(jTextFieldCPFLimite)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCPCUsuario)
                                .addComponent(jLabelCPNUsuario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextFieldCPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonCPUBuscar))
                                .addComponent(jTextFieldCPUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelCPBCodigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPCodigo)
                    .addComponent(jTextFieldCPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPCUsuario)
                    .addComponent(jTextFieldCPUCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCPUBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPUNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPNUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPISBNLibro)
                    .addComponent(jTextFieldCPISBNLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCPLBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPTLibro)
                    .addComponent(jTextFieldCPTLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPBCodigo)
                    .addComponent(jTextFieldCPBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPFPrestamo)
                    .addComponent(jTextFieldCPFPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPFDevolucion)
                    .addComponent(jTextFieldCPFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCPCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCPCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCPCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCPCrearActionPerformed

    private void jButtonCPCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCPCancelarActionPerformed

    private void jTextFieldCPTLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPTLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPTLibroActionPerformed

    private void jTextFieldCPISBNLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPISBNLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPISBNLibroActionPerformed

    private void jTextFieldCPFPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFPrestamoActionPerformed

    private void jTextFieldCPBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPBCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPBCodigoActionPerformed

    private void jButtonCPUBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPUBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCPUBuscarActionPerformed

    private void jButtonCPLBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCPLBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCPLBuscarActionPerformed

    private void jTextFieldCPCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCPCancelar;
    private javax.swing.JButton jButtonCPCrear;
    private javax.swing.JButton jButtonCPLBuscar;
    private javax.swing.JButton jButtonCPUBuscar;
    private javax.swing.JLabel jLabelCPBCodigo;
    private javax.swing.JLabel jLabelCPCUsuario;
    private javax.swing.JLabel jLabelCPCodigo;
    private javax.swing.JLabel jLabelCPFDevolucion;
    private javax.swing.JLabel jLabelCPFPrestamo;
    private javax.swing.JLabel jLabelCPISBNLibro;
    private javax.swing.JLabel jLabelCPNUsuario;
    private javax.swing.JLabel jLabelCPTLibro;
    private javax.swing.JLabel jLabelCrearPrestamo;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldCPBCodigo;
    private javax.swing.JTextField jTextFieldCPCodigo;
    private javax.swing.JTextField jTextFieldCPFLimite;
    private javax.swing.JTextField jTextFieldCPFPrestamo;
    private javax.swing.JTextField jTextFieldCPISBNLibro;
    private javax.swing.JTextField jTextFieldCPTLibro;
    private javax.swing.JTextField jTextFieldCPUCedula;
    private javax.swing.JTextField jTextFieldCPUNombre;
    // End of variables declaration//GEN-END:variables
}
