/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.sistemabiblioteca.principalview;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        fileMenu2 = new javax.swing.JMenu();
        openMenuItem2 = new javax.swing.JMenuItem();
        Buscar1 = new javax.swing.JMenuItem();
        saveAsMenuItem2 = new javax.swing.JMenuItem();
        exitMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        fileMenu3 = new javax.swing.JMenu();
        openMenuItem3 = new javax.swing.JMenuItem();
        Buscar2 = new javax.swing.JMenuItem();
        saveAsMenuItem3 = new javax.swing.JMenuItem();
        exitMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        fileMenu4 = new javax.swing.JMenu();
        openMenuItem4 = new javax.swing.JMenuItem();
        Buscar3 = new javax.swing.JMenuItem();
        saveAsMenuItem4 = new javax.swing.JMenuItem();
        exitMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Prestamo = new javax.swing.JMenu();
        openMenuItem5 = new javax.swing.JMenuItem();
        Buscar4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Devolucion = new javax.swing.JMenu();
        openMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Devolucion1 = new javax.swing.JMenu();
        openMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Autor");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Crear");
        fileMenu.add(openMenuItem);

        Buscar.setMnemonic('s');
        Buscar.setText("Buscar");
        fileMenu.add(Buscar);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Actualizar");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Borrar");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        fileMenu.add(exitMenuItem);

        jMenuItem1.setText("Listar");
        fileMenu.add(jMenuItem1);

        menuBar.add(fileMenu);

        fileMenu2.setMnemonic('f');
        fileMenu2.setText("Libro");

        openMenuItem2.setMnemonic('o');
        openMenuItem2.setText("Crear");
        fileMenu2.add(openMenuItem2);

        Buscar1.setMnemonic('s');
        Buscar1.setText("Buscar");
        fileMenu2.add(Buscar1);

        saveAsMenuItem2.setMnemonic('a');
        saveAsMenuItem2.setText("Actualizar");
        fileMenu2.add(saveAsMenuItem2);

        exitMenuItem2.setMnemonic('x');
        exitMenuItem2.setText("Borrar");
        exitMenuItem2.addActionListener(this::exitMenuItem2ActionPerformed);
        fileMenu2.add(exitMenuItem2);

        jMenuItem2.setText("Listar");
        fileMenu2.add(jMenuItem2);

        menuBar.add(fileMenu2);

        fileMenu3.setMnemonic('f');
        fileMenu3.setText("Bibliotecario");

        openMenuItem3.setMnemonic('o');
        openMenuItem3.setText("Crear");
        fileMenu3.add(openMenuItem3);

        Buscar2.setMnemonic('s');
        Buscar2.setText("Buscar");
        fileMenu3.add(Buscar2);

        saveAsMenuItem3.setMnemonic('a');
        saveAsMenuItem3.setText("Actualizar");
        fileMenu3.add(saveAsMenuItem3);

        exitMenuItem3.setMnemonic('x');
        exitMenuItem3.setText("Borrar");
        exitMenuItem3.addActionListener(this::exitMenuItem3ActionPerformed);
        fileMenu3.add(exitMenuItem3);

        jMenuItem3.setText("Listar");
        fileMenu3.add(jMenuItem3);

        menuBar.add(fileMenu3);

        fileMenu4.setMnemonic('f');
        fileMenu4.setText("Usuario");

        openMenuItem4.setMnemonic('o');
        openMenuItem4.setText("Crear");
        fileMenu4.add(openMenuItem4);

        Buscar3.setMnemonic('s');
        Buscar3.setText("Buscar");
        fileMenu4.add(Buscar3);

        saveAsMenuItem4.setMnemonic('a');
        saveAsMenuItem4.setText("Actualizar");
        fileMenu4.add(saveAsMenuItem4);

        exitMenuItem4.setMnemonic('x');
        exitMenuItem4.setText("Borrar");
        exitMenuItem4.addActionListener(this::exitMenuItem4ActionPerformed);
        fileMenu4.add(exitMenuItem4);

        jMenuItem4.setText("Listar");
        fileMenu4.add(jMenuItem4);

        menuBar.add(fileMenu4);

        Prestamo.setMnemonic('f');
        Prestamo.setText("Prestamo");

        openMenuItem5.setMnemonic('o');
        openMenuItem5.setText("Crear");
        Prestamo.add(openMenuItem5);

        Buscar4.setMnemonic('s');
        Buscar4.setText("Buscar");
        Prestamo.add(Buscar4);

        jMenuItem5.setText("Listar");
        Prestamo.add(jMenuItem5);

        menuBar.add(Prestamo);

        Devolucion.setMnemonic('f');
        Devolucion.setText("Devolucion");

        openMenuItem6.setMnemonic('o');
        openMenuItem6.setText("Crear");
        Devolucion.add(openMenuItem6);

        jMenuItem6.setText("Listar");
        Devolucion.add(jMenuItem6);

        menuBar.add(Devolucion);

        Devolucion1.setMnemonic('f');
        Devolucion1.setText("Idioma");

        openMenuItem7.setMnemonic('o');
        openMenuItem7.setText("Español");
        Devolucion1.add(openMenuItem7);

        jMenuItem7.setText("Ingles");
        Devolucion1.add(jMenuItem7);

        menuBar.add(Devolucion1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void exitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem2ActionPerformed

    private void exitMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem3ActionPerformed

    private void exitMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Buscar1;
    private javax.swing.JMenuItem Buscar2;
    private javax.swing.JMenuItem Buscar3;
    private javax.swing.JMenuItem Buscar4;
    private javax.swing.JMenu Devolucion;
    private javax.swing.JMenu Devolucion1;
    private javax.swing.JMenu Prestamo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem2;
    private javax.swing.JMenuItem exitMenuItem3;
    private javax.swing.JMenuItem exitMenuItem4;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu2;
    private javax.swing.JMenu fileMenu3;
    private javax.swing.JMenu fileMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem2;
    private javax.swing.JMenuItem openMenuItem3;
    private javax.swing.JMenuItem openMenuItem4;
    private javax.swing.JMenuItem openMenuItem5;
    private javax.swing.JMenuItem openMenuItem6;
    private javax.swing.JMenuItem openMenuItem7;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem2;
    private javax.swing.JMenuItem saveAsMenuItem3;
    private javax.swing.JMenuItem saveAsMenuItem4;
    // End of variables declaration//GEN-END:variables

}
